site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

# https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
# https://squidfunk.github.io/mkdocs-material/getting-started/
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - typescript
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme
    palette:
        primary: "lime"
        accent: "lime"
    analytics:
        gtag: G-ABC123

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# minify: https://github.com/byrnereese/mkdocs-minify-plugin
# use this plugin will increase build time and decrease browser render time
# plugins:
#     - search # necessary for search to work
#     - minify:
#         minify_html: false
#         minify_js: true
#         minify_css: true
#         htmlmin_opts:
#             remove_comments: true
#         js_files:
#             - /js/history.js
#             - /js/baidu-statistics.js
# extra:
#   search:
#     language: 'jp'

# extra_javascript:
#     - 'js/baidu-statistics.min.js'
#     - 'js/history.min.js'

# Page tree
nav:
    - 'index': 'index.md'
    - '00-TypeScript 官方入门教程': '00-TypeScript 官方入门教程.md'
    - '01-简介': '01-简介.md'
    - '02-基础': '02-基础.md'
    - '03-进阶': '03-进阶.md'
    - '04-工程化开发-测试编译': '04-工程化开发-测试编译.md'
    - '10-Typescript常见问题整理': '10-Typescript常见问题整理.md'
    - 'TS 常见问题整理': 'TS 常见问题整理.md'
    - 'TS+JEST 单元测试配置文件说明': 'TS+JEST 单元测试配置文件说明.md'
    - 'TypeScript编译器-默认情况下不启用downlevelIteration': 'TypeScript编译器-默认情况下不启用downlevelIteration.md'
    - 'Typescript Use compiler option bug': 'Typescript Use compiler option bug.md'
    - 'Webpack 转译 Typescript 现有方案': 'Webpack 转译 Typescript 现有方案.md'
    - 'typescript 编译选项和配置文件': 'typescript 编译选项和配置文件.md'
    - '文档树': '文档树.md'
    - '网易云课堂TS入门': '网易云课堂TS入门.md'

    - 菜鸟教程:
        - '00-basic': 'runoob/00-basic.md'
        - '01-install': 'runoob/01-install/01-install.md'
        - '02-basic-grammar': 'runoob/02-basic/02-basic-grammar.md'
        - '03-数据类型': 'runoob/03-数据类型.md'
        - '04-变量': 'runoob/04-变量.md'
        - '05-运算符': 'runoob/05-运算符.md'
        - '06-条件语句': 'runoob/06-条件语句.md'
        - '09-数据类型API': 'runoob/09-数据类型API.md'
        - '10-数组对象': 'runoob/10-数组对象.md'
        - '11-map': 'runoob/11-map.md'
        - '12-元组': 'runoob/12-元组.md'
        - '13-接口': 'runoob/13-接口.md'
        - '14-类': 'runoob/14-类.md'
        - '15-命名空间': 'runoob/15-命名空间/15-命名空间.md'
        - '16-模块': 'runoob/16-模块/16-模块.md'
        - '17-声明文件': 'runoob/17-声明文件.md'
