site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
    palette:
        primary: "red"

extra_javascript:
    - 'js/baidu-statistics.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# plugins:
#   - search # necessary for search to work

# extra:
#   search:
#     language: 'jp'

# Page tree
nav:
    - About:
        - '关于我': 'about/README.md'
        - '学习日志': 'about/log.md'
        - '文档结构': 'index.md'
    - Javascript:
        - '近期笔记': 'recent-note.md'
        - 'CommonJS-AMD-CMD': 'CommonJS-AMD-CMD.md'
        - '前端项目结构': 'javascript/前端项目结构.md'
        - 'js判断字符串中是否包含某个字符串': 'javascript/js判断字符串中是否包含某个字符串.md'
        - '通用组件': 'javascript/通用组件.md'
        - '如何写通用组件': 'javascript/如何写通用组件.md'
        - 'ES6 迭代器与生成器': 'javascript/ES6 迭代器与生成器.md'
        - 'ES6-阮一峰': 'javascript/ES6-阮一峰.md'
        - 'ES6newFeature': 'javascript/ES6newFeature.md'
        - 'JS 性能优化': 'javascript/JS 性能优化.md'
        - 'JS-testing': 'javascript/JS-testing.md'
        - 'editor-js': 'javascript/editor-js.md'
        - 'es6': 'javascript/es6.md'
        - '常用到的ES6语法': 'javascript/常用到的ES6语法.md'
        - '前端英语单词': 'javascript/前端英语单词.md'
        - 'JSzip': 'javascript/JSzip.md'
        - 'text-runner': 'javascript/text-runner.md'
        - 'localstorage': 'javascript/localstorage.md'
        - '前端常用工具': 'javascript/前端常用工具.md'
        - '前端监控理论': 'javascript/前端监控理论.md'
    # 第三方库
    # third-part-lib
    - AntDesign:
        - '01-color.md': 'ant-design/01-color.md'
        - '02-border.md': 'ant-design/02-border.md'
        - '03-font.md': 'ant-design/03-font.md'
        - '04-unit.md': 'ant-design/04-unit.md'
        - 'react-00-介绍.md': 'ant-design/react-00-介绍.md'
        - 'react-01-在 create-react-app 中使用.md': 'ant-design/react-01-在 create-react-app 中使用.md'
        - 'react-02-定制主题.md': 'ant-design/react-02-定制主题.md'
    - typescript:
        - '01-简介': 'typescript/01-简介.md'
        - '02-基础': 'typescript/02-基础.md'
        - '03-进阶': 'typescript/03-进阶.md'
        - '04-工程化开发-测试编译': 'typescript/04-工程化开发-测试编译.md'
        - '网易云课堂TS入门': 'typescript/网易云课堂TS入门.md'
        - '01-上手TypeScript': 'typescript/01-上手TypeScript.md'
        - '02-TS-Gulp': 'typescript/02-TS-Gulp.md'
        - '03-JavaScript迁移': 'typescript/03-JavaScript迁移.md'
        - '04-React & Webpack': 'typescript/04-React & Webpack.md'
        - 'TS 常见问题整理': 'typescript/TS 常见问题整理.md'
        - 'TypeScript编译器-downlevelIteration': 'typescript/TypeScript编译器 – 为什么默认情况下不启用downlevelIteration？.md'
        - 'typescript 编译选项和配置文件': 'typescript/typescript 编译选项和配置文件.md'
    - react:
        - 'React & Webpack': 'react/React & Webpack.md'
        - 'React 框架学习笔记': 'react/React 框架学习笔记.md'
        - 'React 视频教程-传智播客': 'react/React 视频教程-传智播客.md'
        - 'react/React 视频教程-技术胖': 'react/React 视频教程-技术胖.md'
        - 'Create-React-App.md': 'react/Create-React-App.md'
        - 'React FAQ.md': 'react/React FAQ.md'
        - 'React Image Lightbox.md': 'react/React Image Lightbox.md'
        - 'React PureComponent 使用指南.md': 'react/React PureComponent 使用指南.md'
        - 'React Router 中文文档（一）.md': 'react/React Router 中文文档（一）.md'
        - 'React Router 中文文档（二）.md': 'react/React Router 中文文档（二）.md'
        - 'React data grid.md': 'react/React data grid.md'
        - 'React 的 PureComponent 与 Component.md': 'react/React 的 PureComponent 与 Component.md'
        - 'React 各种bug 会实时更新.md': 'react/React 各种bug 会实时更新.md'
        - 'React 高阶组件.md': 'react/React 高阶组件.md'
        - 'React 操作元素的API.md': 'react/React 操作元素的API.md'
        - 'React 中的事件处理.md': 'react/React 中的事件处理.md'
        - 'React 强制更新组件.md': 'react/React 强制更新组件.md'
        - 'React-Design Principles.md': 'react/React-Design Principles.md'
        - 'React-Hooks.md': 'react/React-Hooks.md'
        - 'React-Router.md': 'react/React-Router.md'
        - 'React-Select.md': 'react/React-Select.md'
        - 'React-Suspense的实现与探讨.md': 'react/React-Suspense的实现与探讨.md'
        - 'React-advanced-guides.md': 'react/React-advanced-guides.md'
        - 'React-mentions.md': 'react/React-mentions.md'
        - 'React-高阶API.md': 'react/React-高阶API.md'
        - 'React-性能优化.md': 'react/React-性能优化.md'
        - 'React.Children的API.md': 'react/React.Children的API.md'
        - 'React.Component.md': 'react/React.Component.md'
        - 'ReactRouter-阮一峰.md': 'react/ReactRouter-阮一峰.md'
        - 'React事件.md': 'react/React事件.md'
        - 'React数据流.md': 'react/React数据流.md'
        - 'React快捷输入.md': 'react/React快捷输入.md'
        - 'React获取尺寸.md': 'react/React获取尺寸.md'
        - 'React新生命周期--getDerivedStateFromProps.md': 'react/React新生命周期--getDerivedStateFromProps.md'
        - 'React中数据传输.md': 'react/React中数据传输.md'
        - 'React点击事件改变DOM方法.md': 'react/React点击事件改变DOM方法.md'
        - 'React生命周期流程图.md': 'react/React生命周期流程图.md'
        - 'Refs & DOM.md': 'react/Refs & DOM.md'
        - 'TS-React-Webpack.md': 'react/TS-React-Webpack.md'
        - 'VS Code 快捷输入.md': 'react/VS Code 快捷输入.md'
        - 'getDerivedStateFromProps的使用.md': 'react/getDerivedStateFromProps的使用.md'
        - 'gojs-react.md': 'react/gojs-react.md'
        - 'jsx语法.md': 'react/jsx语法.md'
        - 'react 中通过ref获取高阶（HOC）子组件实例的解决方案.md': 'react/react 中通过ref获取高阶（HOC）子组件实例的解决方案.md'
        - 'react 项目结构及编码规范.md': 'react/react 项目结构及编码规范.md'
        - 'react+graphql实现github dashboard.md': 'react/react+graphql实现github dashboard.md'
        - 'react-lazy-load.md': 'react/react-lazy-load.md'
        - 'react-motion.md': 'react/react-motion.md'
        - 'react-redux.md': 'react/react-redux.md'
        - 'react-responsive.md': 'react/react-responsive.md'
        - 'react-transition-group-动画效果.md': 'react/react-transition-group-动画效果.md'
        - 'reactjs源码分析-上篇（首次渲染实现原理）.md': 'react/reactjs源码分析-上篇（首次渲染实现原理）.md'
        - 'reactjs源码分析-下篇（更新机制实现原理）.md': 'react/reactjs源码分析-下篇（更新机制实现原理）.md'
        - 'reactstrap.md': 'react/reactstrap.md'
        - 'readme.md': 'react/readme.md'
        - '对React children理解.md': 'react/对React children理解.md'
        - 'TS-React-Webpack.md': 'react/TS-React-Webpack.md'
    - 工程化:
        - 'BUG-Auto packing the repository in background for optimum performance.md': 'git/BUG-Auto packing the repository in background for optimum performance.md'
        - 'Translation.md': 'git/Translation.md'
        - 'markdown-new-style.md': 'git/markdown-new-style.md'
    - 课程笔记:
        - '00-目录.md': 'netease/00-目录.md'
        - '02-v8引擎回收内存简介.md': 'netease/02-v8引擎回收内存简介.md'
        - '03-node下面的Restful实现.md': 'netease/03-node下面的Restful实现.md'
        - '04-编程思想的提升—如何提高我们代码的可扩展性.md': 'netease/04-编程思想的提升—如何提高我们代码的可扩展性.md'
        - '06-浏览器渲染原理和ssr.md': 'netease/06-浏览器渲染原理和ssr.md'
        - '07-网易真实项目webpack配置解析.md': 'netease/07-网易真实项目webpack配置解析.md'
        - '08-从架构分析API层.md': 'netease/08-从架构分析API层.md'
        - '09-前端负责人的工作内容.md': 'netease/09-前端负责人的工作内容.md'
        - '10-分析源码学架构.md': 'netease/10-分析源码学架构.md'
        - '11-设计模式高质量代码.md': 'netease/11-设计模式高质量代码.md'
        - '12-nodeJS+MongoDB登录系统.md': 'netease/12-nodeJS+MongoDB登录系统.md'
        - '12-nodejs-mongodb-mongoose.md': 'netease/12-nodejs-mongodb-mongoose.md'
        - '13-使用VUE创建组件（没学完）.md': 'netease/13-使用VUE创建组件（没学完）.md'
        - '16-构建自己的脚手架工具.md': 'netease/16-构建自己的脚手架工具.md'
        - '17-webpack编译原理分析.md': 'netease/17-webpack编译原理分析.md'
        - '20-组件封装的基本技能-VUE（没学完）.md': 'netease/20-组件封装的基本技能-VUE（没学完）.md'
        - '21-ssr.md': 'netease/21-ssr.md'
        - '24-单元测试如何做.md': 'netease/24-单元测试如何做.md'
        - '25-基于NodeJS打造Web架构中间层.md': 'netease/25-基于NodeJS打造Web架构中间层.md'
        - '26-webpack的高级技巧.md': 'netease/26-webpack的高级技巧.md'
    
    - React 官方文档:
        - 'readme.md': 'react/react-all/中文文档全部/readme.md'
        - '0 目录.md': 'react/react-all/中文文档全部/0 目录.md'
        - '2-10 状态提升.md': 'react/react-all/中文文档全部/2-10 状态提升.md'
        - '2-11 组合 vs 继承.md': 'react/react-all/中文文档全部/2-11 组合 vs 继承.md'
        - '2-12 React 哲学.md': 'react/react-all/中文文档全部/2-12 React 哲学.md'
        - '2-4 组件 & Props.md': 'react/react-all/中文文档全部/2-4 组件 & Props.md'
        - '2-5 State & 生命周期.md': 'react/react-all/中文文档全部/2-5 State & 生命周期.md'
        - '2-6 事件处理.md': 'react/react-all/中文文档全部/2-6 事件处理.md'
        - '2-7 条件渲染.md': 'react/react-all/中文文档全部/2-7 条件渲染.md'
        - '2-8 列表 & Keys.md': 'react/react-all/中文文档全部/2-8 列表 & Keys.md'
        - '2-9 表单.md': 'react/react-all/中文文档全部/2-9 表单.md'
        - '3-1 无障碍辅助功能.md': 'react/react-all/中文文档全部/3-1 无障碍辅助功能.md'
        - '3-10 Optimizing Performance.md': 'react/react-all/中文文档全部/3-10 Optimizing Performance.md'
        - '3-11 Portals.md': 'react/react-all/中文文档全部/3-11 Portals.md'
        - '3-12 Profiler API.md': 'react/react-all/中文文档全部/3-12 Profiler API.md'
        - '3-13 不使用 ES6.md': 'react/react-all/中文文档全部/3-13 不使用 ES6.md'
        - '3-14 不使用 JSX 的 React.md': 'react/react-all/中文文档全部/3-14 不使用 JSX 的 React.md'
        - '3-15 协调.md': 'react/react-all/中文文档全部/3-15 协调.md'
        - '3-16 Refs and the DOM.md': 'react/react-all/中文文档全部/3-16 Refs and the DOM.md'
        - '3-17 Render Props.md': 'react/react-all/中文文档全部/3-17 Render Props.md'
        - '3-18 静态类型检查.md': 'react/react-all/中文文档全部/3-18 静态类型检查.md'
        - '3-19 严格模式.md': 'react/react-all/中文文档全部/3-19 严格模式.md'
        - '3-2 代码打包分割.md': 'react/react-all/中文文档全部/3-2 代码打包分割.md'
        - '3-20 使用 PropTypes 进行类型检查.md': 'react/react-all/中文文档全部/3-20 使用 PropTypes 进行类型检查.md'
        - '3-21 非受控组件.md': 'react/react-all/中文文档全部/3-21 非受控组件.md'
        - '3-22 Web Components.md': 'react/react-all/中文文档全部/3-22 Web Components.md'
        - '3-3 Context.md': 'react/react-all/中文文档全部/3-3 Context.md'
        - '3-4 错误边界.md': 'react/react-all/中文文档全部/3-4 错误边界.md'
        - '3-5 Refs 转发.md': 'react/react-all/中文文档全部/3-5 Refs 转发.md'
        - '3-6 Fragments.md': 'react/react-all/中文文档全部/3-6 Fragments.md'
        - '3-7 高阶组件.md': 'react/react-all/中文文档全部/3-7 高阶组件.md'
        - '3-8 与第三方库协同.md': 'react/react-all/中文文档全部/3-8 与第三方库协同.md'
        - '3-9 深入 JSX.md': 'react/react-all/中文文档全部/3-9 深入 JSX.md'
        - '4-1 React 顶层 API.md': 'react/react-all/中文文档全部/4-1 React 顶层 API.md'
        - '4-10 React 术语词汇表.md': 'react/react-all/中文文档全部/4-10 React 术语词汇表.md'
        - '4-2 React.Component.md': 'react/react-all/中文文档全部/4-2 React.Component.md'
        - '4-3 ReactDOM.md': 'react/react-all/中文文档全部/4-3 ReactDOM.md'
        - '4-4 ReactDOMServer.md': 'react/react-all/中文文档全部/4-4 ReactDOMServer.md'
        - '4-5 DOM 元素.md': 'react/react-all/中文文档全部/4-5 DOM 元素.md'
        - '4-6 合成事件.md': 'react/react-all/中文文档全部/4-6 合成事件.md'
        - '4-7 Test Utilities.md': 'react/react-all/中文文档全部/4-7 Test Utilities.md'
        - '4-8 Test Renderer.md': 'react/react-all/中文文档全部/4-8 Test Renderer.md'
        - '4-9 JavaScript 环境要求.md': 'react/react-all/中文文档全部/4-9 JavaScript 环境要求.md'
        - '5-1 Hook 简介.md': 'react/react-all/中文文档全部/5-1 Hook 简介.md'
        - '5-2 Hook 概览.md': 'react/react-all/中文文档全部/5-2 Hook 概览.md'
        - '5-3 使用 State Hook.md': 'react/react-all/中文文档全部/5-3 使用 State Hook.md'
        - '5-4 使用 Effect Hook.md': 'react/react-all/中文文档全部/5-4 使用 Effect Hook.md'
        - '5-5 Hook 规则.md': 'react/react-all/中文文档全部/5-5 Hook 规则.md'
        - '5-6 自定义 Hook.md': 'react/react-all/中文文档全部/5-6 自定义 Hook.md'
        - '5-7 Hook API 索引.md': 'react/react-all/中文文档全部/5-7 Hook API 索引.md'
        - '5-8 Hooks FAQ.md': 'react/react-all/中文文档全部/5-8 Hooks FAQ.md'
        - '6-1 测试概览.md': 'react/react-all/中文文档全部/6-1 测试概览.md'
        - '6-2 测试技巧.md': 'react/react-all/中文文档全部/6-2 测试技巧.md'
        - '6-3 测试环境.md': 'react/react-all/中文文档全部/6-3 测试环境.md'
        - '7-1 AJAX and APIs.md': 'react/react-all/中文文档全部/7-1 AJAX and APIs.md'
        - '7-2 Babel，JSX 及构建过程.md': 'react/react-all/中文文档全部/7-2 Babel，JSX 及构建过程.md'
        - '7-3 传递函数给组件.md': 'react/react-all/中文文档全部/7-3 传递函数给组件.md'
        - '7-4 组件状态.md': 'react/react-all/中文文档全部/7-4 组件状态.md'
        - '7-5 样式与 CSS.md': 'react/react-all/中文文档全部/7-5 样式与 CSS.md'
        - '7-6 项目文件结构.md': 'react/react-all/中文文档全部/7-6 项目文件结构.md'
        - '7-7 Virtual DOM 及内核.md': 'react/react-all/中文文档全部/7-7 Virtual DOM 及内核.md'
        - 'accessibility.md': 'react/react-all/英文文档/accessibility.md'
        - 'add-react-to-a-new-app.md': 'react/react-all/英文文档/add-react-to-a-new-app.md'
        - 'add-react-to-an-existing-app.md': 'react/react-all/英文文档/add-react-to-an-existing-app.md'
        - 'addons-animation.md': 'react/react-all/英文文档/addons-animation.md'
        - 'addons-create-fragment.md': 'react/react-all/英文文档/addons-create-fragment.md'
        - 'addons-perf.md': 'react/react-all/英文文档/addons-perf.md'
        - 'addons-pure-render-mixin.md': 'react/react-all/英文文档/addons-pure-render-mixin.md'
        - 'addons-shallow-compare.md': 'react/react-all/英文文档/addons-shallow-compare.md'
        - 'addons-shallow-renderer.md': 'react/react-all/英文文档/addons-shallow-renderer.md'
        - 'addons-test-utils.md': 'react/react-all/英文文档/addons-test-utils.md'
        - 'addons-two-way-binding-helpers.md': 'react/react-all/英文文档/addons-two-way-binding-helpers.md'
        - 'addons-update.md': 'react/react-all/英文文档/addons-update.md'
        - 'addons.md': 'react/react-all/英文文档/addons.md'
        - 'cdn-links.md': 'react/react-all/英文文档/cdn-links.md'
        - 'code-splitting.md': 'react/react-all/英文文档/code-splitting.md'
        - 'codebase-overview.md': 'react/react-all/英文文档/codebase-overview.md'
        - 'components-and-props.md': 'react/react-all/英文文档/components-and-props.md'
        - 'composition-vs-inheritance.md': 'react/react-all/英文文档/composition-vs-inheritance.md'
        - 'conditional-rendering.md': 'react/react-all/英文文档/conditional-rendering.md'
        - 'context.md': 'react/react-all/英文文档/context.md'
        - 'create-a-new-react-app.md': 'react/react-all/英文文档/create-a-new-react-app.md'
        - 'cross-origin-errors.md': 'react/react-all/英文文档/cross-origin-errors.md'
        - 'design-principles.md': 'react/react-all/英文文档/design-principles.md'
        - 'error-boundaries.md': 'react/react-all/英文文档/error-boundaries.md'
        - 'error-decoder.md': 'react/react-all/英文文档/error-decoder.md'
        - 'faq-ajax.md': 'react/react-all/英文文档/faq-ajax.md'
        - 'faq-build.md': 'react/react-all/英文文档/faq-build.md'
        - 'faq-functions.md': 'react/react-all/英文文档/faq-functions.md'
        - 'faq-internals.md': 'react/react-all/英文文档/faq-internals.md'
        - 'faq-state.md': 'react/react-all/英文文档/faq-state.md'
        - 'faq-structure.md': 'react/react-all/英文文档/faq-structure.md'
        - 'faq-styling.md': 'react/react-all/英文文档/faq-styling.md'
        - 'forms.md': 'react/react-all/英文文档/forms.md'
        - 'forwarding-refs.md': 'react/react-all/英文文档/forwarding-refs.md'
        - 'fragments.md': 'react/react-all/英文文档/fragments.md'
        - 'getting-started.md': 'react/react-all/英文文档/getting-started.md'
        - 'handling-events.md': 'react/react-all/英文文档/handling-events.md'
        - 'higher-order-components.md': 'react/react-all/英文文档/higher-order-components.md'
        - 'hooks-custom.md': 'react/react-all/英文文档/hooks-custom.md'
        - 'hooks-effect.md': 'react/react-all/英文文档/hooks-effect.md'
        - 'hooks-faq.md': 'react/react-all/英文文档/hooks-faq.md'
        - 'hooks-intro.md': 'react/react-all/英文文档/hooks-intro.md'
        - 'hooks-overview.md': 'react/react-all/英文文档/hooks-overview.md'
        - 'hooks-reference.md': 'react/react-all/英文文档/hooks-reference.md'
        - 'hooks-rules.md': 'react/react-all/英文文档/hooks-rules.md'
        - 'hooks-state.md': 'react/react-all/英文文档/hooks-state.md'
        - 'how-to-contribute.md': 'react/react-all/英文文档/how-to-contribute.md'
        - 'implementation-notes.md': 'react/react-all/英文文档/implementation-notes.md'
        - 'installation.md': 'react/react-all/英文文档/installation.md'
        - 'integrating-with-other-libraries.md': 'react/react-all/英文文档/integrating-with-other-libraries.md'
        - 'introducing-jsx.md': 'react/react-all/英文文档/introducing-jsx.md'
        - 'jsx-in-depth.md': 'react/react-all/英文文档/jsx-in-depth.md'
        - 'legacy-context.md': 'react/react-all/英文文档/legacy-context.md'
        - 'lifting-state-up.md': 'react/react-all/英文文档/lifting-state-up.md'
        - 'lists-and-keys.md': 'react/react-all/英文文档/lists-and-keys.md'
        - 'optimizing-performance.md': 'react/react-all/英文文档/optimizing-performance.md'
        - 'portals.md': 'react/react-all/英文文档/portals.md'
        - 'react-without-es6.md': 'react/react-all/英文文档/react-without-es6.md'
        - 'react-without-jsx.md': 'react/react-all/英文文档/react-without-jsx.md'
        - 'reconciliation.md': 'react/react-all/英文文档/reconciliation.md'
        - 'reference-dom-elements.md': 'react/react-all/英文文档/reference-dom-elements.md'
        - 'reference-events.md': 'react/react-all/英文文档/reference-events.md'
        - 'reference-glossary.md': 'react/react-all/英文文档/reference-glossary.md'
        - 'reference-javascript-environment-requirements.md': 'react/react-all/英文文档/reference-javascript-environment-requirements.md'
        - 'reference-pure-render-mixin.md': 'react/react-all/英文文档/reference-pure-render-mixin.md'
        - 'reference-react-component.md': 'react/react-all/英文文档/reference-react-component.md'
        - 'reference-react-dom-server.md': 'react/react-all/英文文档/reference-react-dom-server.md'
        - 'reference-react-dom.md': 'react/react-all/英文文档/reference-react-dom.md'
        - 'reference-react.md': 'react/react-all/英文文档/reference-react.md'
        - 'reference-test-renderer.md': 'react/react-all/英文文档/reference-test-renderer.md'
        - 'refs-and-the-dom.md': 'react/react-all/英文文档/refs-and-the-dom.md'
        - 'render-props.md': 'react/react-all/英文文档/render-props.md'
        - 'rendering-elements.md': 'react/react-all/英文文档/rendering-elements.md'
        - 'state-and-lifecycle.md': 'react/react-all/英文文档/state-and-lifecycle.md'
        - 'static-type-checking.md': 'react/react-all/英文文档/static-type-checking.md'
        - 'strict-mode.md': 'react/react-all/英文文档/strict-mode.md'
        - 'thinking-in-react.md': 'react/react-all/英文文档/thinking-in-react.md'
        - 'typechecking-with-proptypes.md': 'react/react-all/英文文档/typechecking-with-proptypes.md'
        - 'uncontrolled-components.md': 'react/react-all/英文文档/uncontrolled-components.md'
        - 'web-components.md': 'react/react-all/英文文档/web-components.md'
        - '01-readme.md': 'react/react-all/react-dnd/01-readme.md'
        - '02-quickstart.md': 'react/react-all/react-dnd/02-quickstart.md'
        - '03-Overview.md': 'react/react-all/react-dnd/03-Overview.md'
        - 'API.md': 'react/react-all/react-dnd/API.md'
        - 'React DnD.md': 'react/react-all/react-dnd/React DnD.md'
        - 'Testing.md': 'react/react-all/react-dnd/Testing.md'
        - 'Tutorial.md': 'react/react-all/react-dnd/Tutorial.md'
        - 'react-dnd-DragLayer.md': 'react/react-all/react-dnd/react-dnd-DragLayer.md'
        - 'react-dnd-DragSource.md': 'react/react-all/react-dnd/react-dnd-DragSource.md'
        - 'react-dnd-DropTarget.md': 'react/react-all/react-dnd/react-dnd-DropTarget.md'
        - 'react-dnd.md': 'react/react-all/react-dnd/react-dnd.md'
        - 'react-dnd使用手记.md': 'react/react-all/react-dnd/react-dnd使用手记.md'
