site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
    palette:
        primary: "red"

extra_javascript:
    - 'js/baidu-statistics.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# plugins:
#   - search # necessary for search to work

# extra:
#   search:
#     language: 'jp'

# Page tree
nav:
    - About:
        - '关于我': 'about/README.md'
        - '学习日志': 'about/log.md'
        - '文档结构': 'index.md'
    - Javascript:
        - 'ES6 迭代器与生成器': 'javascript/ES6 迭代器与生成器.md'
        - 'ES6-阮一峰': 'javascript/ES6-阮一峰.md'
        - 'ES6newFeature': 'javascript/ES6newFeature.md'
        - 'JS 性能优化': 'javascript/JS 性能优化.md'
        - 'JS-testing': 'javascript/JS-testing.md'
        - 'editor-js': 'javascript/editor-js.md'
        - 'es6': 'javascript/es6.md'
        - '常用到的ES6语法': 'javascript/常用到的ES6语法.md'
        - '前端英语单词': 'javascript/前端英语单词.md'
    - typescript:
        - '01-简介': 'typescript/01-简介.md'
        - '02-基础': 'typescript/02-基础.md'
        - '03-进阶': 'typescript/03-进阶.md'
        - '04-工程化开发-测试编译': 'typescript/04-工程化开发-测试编译.md'
        - '网易云课堂TS入门': 'typescript/网易云课堂TS入门.md'
        - '01-上手TypeScript': 'typescript/01-上手TypeScript.md'
        - '02-TS-Gulp': 'typescript/02-TS-Gulp.md'
        - '03-JavaScript迁移': 'typescript/03-JavaScript迁移.md'
        - '04-React & Webpack': 'typescript/04-React & Webpack.md'
        - 'TS 常见问题整理': 'typescript/TS 常见问题整理.md'
        - 'TypeScript编译器-downlevelIteration': 'typescript/TypeScript编译器 – 为什么默认情况下不启用downlevelIteration？.md'
        - 'typescript 编译选项和配置文件': 'typescript/typescript 编译选项和配置文件.md'
    - react:
        - 'Create-React-App.md': 'react/Create-React-App.md'
        - 'React Data grade.md': 'react/React Data grade.md'
        - 'React FAQ.md': 'react/React FAQ.md'
        - 'React Image Lightbox.md': 'react/React Image Lightbox.md'
        - 'React PureComponent 使用指南.md': 'react/React PureComponent 使用指南.md'
        - 'React Router 中文文档（一）.md': 'react/React Router 中文文档（一）.md'
        - 'React Router 中文文档（二）.md': 'react/React Router 中文文档（二）.md'
        - 'React data grid.md': 'react/React data grid.md'
        - 'React 的 PureComponent 与 Component.md': 'react/React 的 PureComponent 与 Component.md'
        - 'React 各种bug 会实时更新.md': 'react/React 各种bug 会实时更新.md'
        - 'React 高阶组件.md': 'react/React 高阶组件.md'
        - 'React 操作元素的API.md': 'react/React 操作元素的API.md'
        - 'React 中的事件处理.md': 'react/React 中的事件处理.md'
        - 'React 强制更新组件.md': 'react/React 强制更新组件.md'
        - 'React-Design Principles.md': 'react/React-Design Principles.md'
        - 'React-Hooks.md': 'react/React-Hooks.md'
        - 'React-Router.md': 'react/React-Router.md'
        - 'React-Select.md': 'react/React-Select.md'
        - 'React-Suspense的实现与探讨-没看明白.md': 'react/React-Suspense的实现与探讨-没看明白.md'
        - 'React-Suspense的实现与探讨.md': 'react/React-Suspense的实现与探讨.md'
        - 'React-advanced-guides.md': 'react/React-advanced-guides.md'
        - 'React-mentions.md': 'react/React-mentions.md'
        - 'React-高阶API.md': 'react/React-高阶API.md'
        - 'React-性能优化.md': 'react/React-性能优化.md'
        - 'React.Children的API.md': 'react/React.Children的API.md'
        - 'React.Component.md': 'react/React.Component.md'
        - 'React.children介绍.md': 'react/React.children介绍.md'
        - 'ReactRouter-阮一峰.md': 'react/ReactRouter-阮一峰.md'
        - 'React事件.md': 'react/React事件.md'
        - 'React数据流.md': 'react/React数据流.md'
        - 'React快捷输入.md': 'react/React快捷输入.md'
        - 'React获取尺寸.md': 'react/React获取尺寸.md'
        - 'React新生命周期--getDerivedStateFromProps.md': 'react/React新生命周期--getDerivedStateFromProps.md'
        - 'React中数据传输.md': 'react/React中数据传输.md'
        - 'React点击事件改变DOM方法.md': 'react/React点击事件改变DOM方法.md'
        - 'React生命周期流程图.md': 'react/React生命周期流程图.md'
        - 'Refs & DOM.md': 'react/Refs & DOM.md'
        - 'TS-React-Webpack.md': 'react/TS-React-Webpack.md'
        - 'VS Code 快捷输入.md': 'react/VS Code 快捷输入.md'
        - 'getDerivedStateFromProps的使用.md': 'react/getDerivedStateFromProps的使用.md'
        - 'gojs-react.md': 'react/gojs-react.md'
        - 'jsx语法.md': 'react/jsx语法.md'
        - 'react 中通过ref获取高阶（HOC）子组件实例的解决方案.md': 'react/react 中通过ref获取高阶（HOC）子组件实例的解决方案.md'
        - 'react 项目结构及编码规范.md': 'react/react 项目结构及编码规范.md'
        - 'react+graphql实现github dashboard.md': 'react/react+graphql实现github dashboard.md'
        - 'react-all': 'react/react-all'
        - 'react-lazy-load.md': 'react/react-lazy-load.md'
        - 'react-mentions-en.md': 'react/react-mentions-en.md'
        - 'react-motion.md': 'react/react-motion.md'
        - 'react-redux.md': 'react/react-redux.md'
        - 'react-responsive.md': 'react/react-responsive.md'
        - 'react-transition-group-动画效果.md': 'react/react-transition-group-动画效果.md'
        - 'react-transition-group.md': 'react/react-transition-group.md'
        - 'reactjs源码分析-上篇（首次渲染实现原理）.md': 'react/reactjs源码分析-上篇（首次渲染实现原理）.md'
        - 'reactjs源码分析-下篇（更新机制实现原理）.md': 'react/reactjs源码分析-下篇（更新机制实现原理）.md'
        - 'reactstrap.md': 'react/reactstrap.md'
        - 'readme.md': 'react/readme.md'
        - '对React children理解.md': 'react/对React children理解.md'
    - 工程化:
        - 'BUG-Auto packing the repository in background for optimum performance.md': 'git/BUG-Auto packing the repository in background for optimum performance.md'
        - 'Translation.md': 'git/Translation.md'
        - 'docker-basic-use.md': 'git/docker-basic-use.md'
        - 'markdown-new-style.md': 'git/markdown-new-style.md'
        - 'React & Webpack.md': 'project/React & Webpack.md'
        - 'TS-React-Webpack.md': 'project/TS-React-Webpack.md'
        - '前端监控理论.md': 'project/前端监控理论.md'
    - 课程笔记:
        - '00-目录.md': 'netease/00-目录.md'
        - '02-v8引擎回收内存简介.md': 'netease/02-v8引擎回收内存简介.md'
        - '03-node下面的Restful实现.md': 'netease/03-node下面的Restful实现.md'
        - '04-编程思想的提升—如何提高我们代码的可扩展性.md': 'netease/04-编程思想的提升—如何提高我们代码的可扩展性.md'
        - '06-浏览器渲染原理和ssr.md': 'netease/06-浏览器渲染原理和ssr.md'
        - '07-网易真实项目webpack配置解析.md': 'netease/07-网易真实项目webpack配置解析.md'
        - '08-从架构分析API层.md': 'netease/08-从架构分析API层.md'
        - '09-前端负责人的工作内容.md': 'netease/09-前端负责人的工作内容.md'
        - '10-分析源码学架构.md': 'netease/10-分析源码学架构.md'
        - '11-设计模式高质量代码.md': 'netease/11-设计模式高质量代码.md'
        - '12-nodeJS+MongoDB登录系统.md': 'netease/12-nodeJS+MongoDB登录系统.md'
        - '12-nodejs-mongodb-mongoose.md': 'netease/12-nodejs-mongodb-mongoose.md'
        - '13-使用VUE创建组件（没学完）.md': 'netease/13-使用VUE创建组件（没学完）.md'
        - '16-构建自己的脚手架工具.md': 'netease/16-构建自己的脚手架工具.md'
        - '17-webpack编译原理分析.md': 'netease/17-webpack编译原理分析.md'
        - '20-组件封装的基本技能-VUE（没学完）.md': 'netease/20-组件封装的基本技能-VUE（没学完）.md'
        - '21-ssr.md': 'netease/21-ssr.md'
        - '24-单元测试如何做.md': 'netease/24-单元测试如何做.md'
        - '25-基于NodeJS打造Web架构中间层.md': 'netease/25-基于NodeJS打造Web架构中间层.md'
        - '26-webpack的高级技巧.md': 'netease/26-webpack的高级技巧.md'
