site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
    palette:
        primary: "red"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# minify: https://github.com/byrnereese/mkdocs-minify-plugin
# use this plugin will increase build time and decrease browser render time
plugins:
    - search # necessary for search to work
    # - minify:
    #     minify_html: true
    #     minify_js: true
    #     minify_css: true
    #     htmlmin_opts:
    #         remove_comments: true
    #     js_files:
    #         - /js/history.js
    #         - /js/baidu-statistics.js
extra:
  search:
    language: 'jp'

extra_javascript:
    - 'js/baidu-statistics.min.js'
    - 'js/history.min.js'

# Page tree
nav:
    - About:
        - 'README': 'about/README.md'
        - 'index': 'index.md'
    - 笔记:
        - 'algre-note': 'note/algre-note.md'
        - 'frontend-note': 'note/frontend-note.md'
        - 'other-note': 'note/other-note.md'
        - 'think-note': 'note/think-note.md'
        - '提升工作效率': 'note/提升工作效率.md'
    - Javascript:
        - 'CommonJS-AMD-CMD': 'javascript/CommonJS-AMD-CMD.md'
        - 'ES6 迭代器与生成器': 'javascript/ES6 迭代器与生成器.md'
        - 'ES6-阮一峰': 'javascript/ES6-阮一峰.md'
        - 'ES6newFeature': 'javascript/ES6newFeature.md'
        - 'File browser': 'javascript/File browser.md'
        - 'react-dom': 'javascript/ID 问题整理/react-dom.md'
        - 'JS 性能优化': 'javascript/JS 性能优化.md'
        - 'JS-testing': 'javascript/JS-testing.md'
        - 'JSzip': 'javascript/JSzip.md'
        - 'JS的异步操作，浏览器的多线程间的协作': 'javascript/JS的异步操作，浏览器的多线程间的协作.md'
        - 'Math-trunk': 'javascript/Math-trunk.md'
        - 'contentEditable 实现富文本编辑器': 'javascript/contentEditable 实现富文本编辑器.md'
        - 'readme': 'javascript/createJS/readme.md'
        - 'editor-js': 'javascript/editor-js.md'
        - 'iframe': 'javascript/iframe.md'
        - 'js判断字符串中是否包含某个字符串': 'javascript/js判断字符串中是否包含某个字符串.md'
        - 'js双指针': 'javascript/js双指针.md'
        - 'localstorage': 'javascript/localstorage.md'
        - 'text-runner': 'javascript/text-runner.md'
        - 'throttle-lodash': 'javascript/throttle-lodash.md'
        - 'viewerjs': 'javascript/viewerjs.md'
        - 'web-worker': 'javascript/web-worker.md'
        - '内存泄漏': 'javascript/内存泄漏.md'
        - '前端常用工具': 'javascript/前端常用工具.md'
        - '前端监控理论': 'javascript/前端监控理论.md'
        - '前端英语单词': 'javascript/前端英语单词.md'
        - '前端项目结构': 'javascript/前端项目结构.md'
        - '如何写通用组件': 'javascript/如何写通用组件.md'
        - '常用到的ES6语法': 'javascript/常用到的ES6语法.md'
        - '通用组件': 'javascript/通用组件.md'
        - '通用英语单词': 'javascript/通用英语单词.md'
    - 常用第三方库:
        - '000-dir': 'third-part-lib/000-dir.md'
        - '001-anv-g2': 'third-part-lib/001-anv-g2.md'
        - '002-react-image-lightbox': 'third-part-lib/002-react-image-lightbox.md'
        - '003-antd-mobile': 'third-part-lib/003-antd-mobile.md'
        - '004-autoprefixer': 'third-part-lib/004-autoprefixer.md'
        - '005-axios': 'third-part-lib/005-axios.md'
        - '006-deep-copy': 'third-part-lib/006-deep-copy.md'
        - '007-dom-helper': 'third-part-lib/007-dom-helper.md'
        - '008-glamor': 'third-part-lib/008-glamor.md'
        - '009-html2canvas': 'third-part-lib/009-html2canvas.md'
        - '010-i18next': 'third-part-lib/010-i18next.md'
        - '011-i18next-browser-languagedetector': 'third-part-lib/011-i18next-browser-languagedetector.md'
        - '012-i18next-xhr-backend': 'third-part-lib/012-i18next-xhr-backend.md'
        - '013-is-hotkey': 'third-part-lib/013-is-hotkey.md'
        - '014-keymirror': 'third-part-lib/014-keymirror.md'
        - '015-lodash-throttle': 'third-part-lib/015-lodash-throttle.md'
        - '016-promise': 'third-part-lib/016-promise.md'
        - '017-qrcode-react': 'third-part-lib/017-qrcode-react.md'
        - '018-raf': 'third-part-lib/018-raf.md'
        - '022-react-is-deprecated': 'third-part-lib/022-react-is-deprecated.md'
        - '024-React-Sweet-Progress': 'third-part-lib/024-React-Sweet-Progress.md'
        - '025-reactstrap': 'third-part-lib/025-reactstrap.md'
        - '026-reselect': 'third-part-lib/026-reselect.md'
        - '027-ron-react-autocomplete': 'third-part-lib/027-ron-react-autocomplete.md'
        - '028-shallow-equal': 'third-part-lib/028-shallow-equal.md'
        - '030-whatwg-fetch': 'third-part-lib/030-whatwg-fetch.md'
        - '031-babel-cli': 'third-part-lib/031-babel-cli.md'
        - '039-babel-preset-env': 'third-part-lib/039-babel-preset-env.md'
        - '040-babel-preset-react': 'third-part-lib/040-babel-preset-react.md'
        - '100-debug': 'third-part-lib/100-debug.md'
        - '101-number-precision': 'third-part-lib/101-number-precision.md'
        - '102-slugid': 'third-part-lib/102-slugid.md'
        - '103-socket-io-client': 'third-part-lib/103-socket-io-client.md'
        - '168-copy-to-clipboard': 'third-part-lib/168-copy-to-clipboard.md'
        - '175-moment': 'third-part-lib/175-moment.md'
        - '183-react-dnd': 'third-part-lib/183-react-dnd.md'
        - '184-react-dnd-html5-backend': 'third-part-lib/184-react-dnd-html5-backend.md'
        - '186-react-i18next': 'third-part-lib/186-react-i18next.md'
        - '192-react-select': 'third-part-lib/192-react-select.md'
        - '255-connect-multiparty': 'third-part-lib/255-connect-multiparty.md'
        - '256-csv': 'third-part-lib/256-csv.md'
        - '257-date-format': 'third-part-lib/257-date-format.md'
        - '258-detect-character-encoding': 'third-part-lib/258-detect-character-encoding.md'
        - '259-etcd3': 'third-part-lib/259-etcd3.md'
        - '260-express': 'third-part-lib/260-express.md'
        - '261-express-rate-limit': 'third-part-lib/261-express-rate-limit.md'
        - '262-iconv-lite': 'third-part-lib/262-iconv-lite.md'
        - '263-jsonwebtoken': 'third-part-lib/263-jsonwebtoken.md'
        - '264-log4js': 'third-part-lib/264-log4js.md'
        - '265-mysql': 'third-part-lib/265-mysql.md'
        - '266-redis': 'third-part-lib/266-redis.md'
        - '267-request': 'third-part-lib/267-request.md'
        - '268-response-time': 'third-part-lib/268-response-time.md'
        - '269-socket.io': 'third-part-lib/269-socket.io.md'
        - '270-uuid': 'third-part-lib/270-uuid.md'
        - '290-lodash': 'third-part-lib/290-lodash.md'
        - '291-jszip': 'third-part-lib/291-jszip.md'
        - '292-react-is': 'third-part-lib/292-react-is.md'
        - '293-react-intl-universal': 'third-part-lib/293-react-intl-universal.md'
        - '300-dayjs': 'third-part-lib/300-dayjs.md'
    - AntDesign:
        - '01-color': 'ant-design/01-color.md'
        - '02-border': 'ant-design/02-border.md'
        - '03-font': 'ant-design/03-font.md'
        - '04-unit': 'ant-design/04-unit.md'
        - '05-react-介绍': 'ant-design/05-react-介绍.md'
        - '06-react-在 create-react-app 中使用': 'ant-design/06-react-在 create-react-app 中使用.md'
        - '07-react-定制主题': 'ant-design/07-react-定制主题.md'
    - CSS:
        - 'Grid布局': 'css/Grid布局.md'
        - 'word-breakbreak-all和word-wrapbreak-word的区别': 'css/word-breakbreak-all和word-wrapbreak-word的区别.md'
        - 'z-index无效解决': 'css/z-index无效解决.md'
        - 'zindex在iOS系统中的兼容性问题': 'css/zindex在iOS系统中的兼容性问题.md'
        - '粘性定位position-sticky': 'css/粘性定位position-sticky.md'
        - '表情emoji': 'css/表情emoji.md'
    - typescript:
        - '01-上手TypeScript': 'typescript/01-上手TypeScript.md'
        - '01-简介': 'typescript/01-简介.md'
        - '02-TS-Gulp': 'typescript/02-TS-Gulp.md'
        - '02-基础': 'typescript/02-基础.md'
        - '03-JavaScript迁移': 'typescript/03-JavaScript迁移.md'
        - '03-进阶': 'typescript/03-进阶.md'
        - '04-React & Webpack': 'typescript/04-React & Webpack.md'
        - '04-工程化开发-测试编译': 'typescript/04-工程化开发-测试编译.md'
        - 'TS 常见问题整理': 'typescript/TS 常见问题整理.md'
        - 'TypeScript编译器 – 为什么默认情况下不启用downlevelIteration？': 'typescript/TypeScript编译器 – 为什么默认情况下不启用downlevelIteration？.md'
        - 'typescript 编译选项和配置文件': 'typescript/typescript 编译选项和配置文件.md'
        - '网易云课堂TS入门': 'typescript/网易云课堂TS入门.md'
    - react:
        - 'Create-React-App': 'react/Create-React-App.md'
        - 'React & Webpack': 'react/React & Webpack.md'
        - 'React FAQ': 'react/React FAQ.md'
        - 'React Image Lightbox': 'react/React Image Lightbox.md'
        - 'React PureComponent 使用指南': 'react/React PureComponent 使用指南.md'
        - 'React Router 中文文档（一）': 'react/React Router 中文文档（一）.md'
        - 'React Router 中文文档（二）': 'react/React Router 中文文档（二）.md'
        - 'React data grid': 'react/React data grid.md'
        - 'React 中的事件处理': 'react/React 中的事件处理.md'
        - 'React 各种bug 会实时更新': 'react/React 各种bug 会实时更新.md'
        - 'React 强制更新组件': 'react/React 强制更新组件.md'
        - 'React 操作元素的API': 'react/React 操作元素的API.md'
        - 'React 框架学习笔记': 'react/React 框架学习笔记.md'
        - 'React 的 PureComponent 与 Component': 'react/React 的 PureComponent 与 Component.md'
        - 'React 视频教程-传智播客': 'react/React 视频教程-传智播客.md'
        - 'React 视频教程-技术胖': 'react/React 视频教程-技术胖.md'
        - 'React 高阶组件': 'react/React 高阶组件.md'
        - 'React-Design Principles': 'react/React-Design Principles.md'
        - 'React-Hooks': 'react/React-Hooks.md'
        - 'React-Router': 'react/React-Router.md'
        - 'React-Select': 'react/React-Select.md'
        - 'React-Suspense的实现与探讨': 'react/React-Suspense的实现与探讨.md'
        - 'React-advanced-guides': 'react/React-advanced-guides.md'
        - 'React-mentions': 'react/React-mentions.md'
        - 'React-性能优化': 'react/React-性能优化.md'
        - 'React-高阶API': 'react/React-高阶API.md'
        - 'React.Children的API': 'react/React.Children的API.md'
        - 'React.Component': 'react/React.Component.md'
        - 'ReactRouter-阮一峰': 'react/ReactRouter-阮一峰.md'
        - 'React中数据传输': 'react/React中数据传输.md'
        - 'React事件': 'react/React事件.md'
        - 'React快捷输入': 'react/React快捷输入.md'
        - 'React数据流': 'react/React数据流.md'
        - 'React新生命周期--getDerivedStateFromProps': 'react/React新生命周期--getDerivedStateFromProps.md'
        - 'React点击事件改变DOM方法': 'react/React点击事件改变DOM方法.md'
        - 'React生命周期流程图': 'react/React生命周期流程图.md'
        - 'React获取尺寸': 'react/React获取尺寸.md'
        - 'Refs & DOM': 'react/Refs & DOM.md'
        - 'TS-React-Webpack': 'react/TS-React-Webpack.md'
        - 'VS Code 快捷输入': 'react/VS Code 快捷输入.md'
        - 'getDerivedStateFromProps的使用': 'react/getDerivedStateFromProps的使用.md'
        - 'gojs-react': 'react/gojs-react.md'
        - 'jsx语法': 'react/jsx语法.md'
        - 'react 中通过ref获取高阶（HOC）子组件实例的解决方案': 'react/react 中通过ref获取高阶（HOC）子组件实例的解决方案.md'
        - 'react 项目结构及编码规范': 'react/react 项目结构及编码规范.md'
        - 'react+graphql实现github dashboard': 'react/react+graphql实现github dashboard.md'
        - 'react-canvas 调研': 'react/react-canvas/react-canvas 调研.md'
        - 'react-colorful': 'react/react-colorful.md'
        - '01-readme': 'react/react-dnd/01-readme.md'
        - '02-quickstart': 'react/react-dnd/02-quickstart.md'
        - '03-Overview': 'react/react-dnd/03-Overview.md'
        - 'API': 'react/react-dnd/API.md'
        - 'React DnD': 'react/react-dnd/React DnD.md'
        - 'Testing': 'react/react-dnd/Testing.md'
        - 'Tutorial': 'react/react-dnd/Tutorial.md'
        - 'react-dnd-DragLayer': 'react/react-dnd/react-dnd-DragLayer.md'
        - 'react-dnd-DragSource': 'react/react-dnd/react-dnd-DragSource.md'
        - 'react-dnd-DropTarget': 'react/react-dnd/react-dnd-DropTarget.md'
        - 'react-dnd': 'react/react-dnd/react-dnd.md'
        - 'react-dnd使用手记': 'react/react-dnd/react-dnd使用手记.md'
        - 'react-lazy-load': 'react/react-lazy-load.md'
        - 'react-motion': 'react/react-motion.md'
        - 'react-redux': 'react/react-redux.md'
        - 'react-responsive': 'react/react-responsive.md'
        - 'react-transition-group-动画效果': 'react/react-transition-group-动画效果.md'
        - 'reactjs源码分析-上篇（首次渲染实现原理）': 'react/reactjs源码分析-上篇（首次渲染实现原理）.md'
        - 'reactjs源码分析-下篇（更新机制实现原理）': 'react/reactjs源码分析-下篇（更新机制实现原理）.md'
        - 'reactstrap': 'react/reactstrap.md'
        - 'stackoverflow-Highlight text using ReactJS': 'react/stackoverflow-Highlight text using ReactJS.md'
        - '对React children理解': 'react/对React children理解.md'
        - '阮一峰 react 系列教程': 'react/阮一峰 react 系列教程.md'
        - 'react-useRef': 'react/hook/react-useRef.md'
    - 工程化:
        - 'BUG-Auto packing the repository in background for optimum performance': 'git/BUG-Auto packing the repository in background for optimum performance.md'
        - 'HTTP 教程': 'git/HTTP 教程.md'
        - 'Mkdocs-github-blog': 'git/Mkdocs-github-blog.md'
        - 'Mkdocs-guide': 'git/Mkdocs-guide.md'
        - 'Mkdocs-mac-env': 'git/Mkdocs-mac-env.md'
        - 'Nightmare': 'git/Nightmare.md'
        - 'Tencent-review-code': 'git/Tencent-review-code.md'
        - 'Translation': 'git/Translation.md'
        - 'enzyme 简单实践': 'git/enzyme 简单实践.md'
        - 'git-use-process': 'git/git-use-process.md'
        - 'markdown-new-style': 'git/markdown-new-style.md'
        - 'npm link的使用': 'git/npm link的使用.md'
        - 'npm package-lock的管理': 'git/npm package-lock的管理.md'
        - 'npm 发布两步验证': 'git/npm 发布两步验证.md'
        - 'npm 学习': 'git/npm 学习.md'
        - 'npx': 'git/npx.md'
        - 'yalc': 'git/yalc.md'
        - '正则表达式': 'git/正则表达式.md'
        - '第三方工具 LOCALFORAGE': 'git/第三方工具 LOCALFORAGE.md'
        - '网易云-Webpack 打包工具简单使用': 'git/网易云-Webpack 打包工具简单使用.md'
        - '网页性能管理详解': 'git/网页性能管理详解.md'
    - react中文官方文档:
        - '0 目录': 'react-official-zh/0 目录.md'
        - '2-11 组合 vs 继承': 'react-official-zh/2-11 组合 vs 继承.md'
        - '2-12 React 哲学': 'react-official-zh/2-12 React 哲学.md'
        - '2-4 组件 & Props': 'react-official-zh/2-4 组件 & Props.md'
        - '2-5 State & 生命周期': 'react-official-zh/2-5 State & 生命周期.md'
        - '2-6 事件处理': 'react-official-zh/2-6 事件处理.md'
        - '2-7 条件渲染': 'react-official-zh/2-7 条件渲染.md'
        - '2-8 列表 & Keys': 'react-official-zh/2-8 列表 & Keys.md'
        - '2-9 表单': 'react-official-zh/2-9 表单.md'
        - '3-1 无障碍辅助功能': 'react-official-zh/3-1 无障碍辅助功能.md'
        - '3-10 Optimizing Performance': 'react-official-zh/3-10 Optimizing Performance.md'
        - '3-11 Portals': 'react-official-zh/3-11 Portals.md'
        - '3-12 Profiler API': 'react-official-zh/3-12 Profiler API.md'
        - '3-13 不使用 ES6': 'react-official-zh/3-13 不使用 ES6.md'
        - '3-14 不使用 JSX 的 React': 'react-official-zh/3-14 不使用 JSX 的 React.md'
        - '3-15 协调': 'react-official-zh/3-15 协调.md'
        - '3-16 Refs and the DOM': 'react-official-zh/3-16 Refs and the DOM.md'
        - '3-17 Render Props': 'react-official-zh/3-17 Render Props.md'
        - '3-18 静态类型检查': 'react-official-zh/3-18 静态类型检查.md'
        - '3-19 严格模式': 'react-official-zh/3-19 严格模式.md'
        - '3-2 代码打包分割': 'react-official-zh/3-2 代码打包分割.md'
        - '3-20 使用 PropTypes 进行类型检查': 'react-official-zh/3-20 使用 PropTypes 进行类型检查.md'
        - '3-21 非受控组件': 'react-official-zh/3-21 非受控组件.md'
        - '3-22 Web Components': 'react-official-zh/3-22 Web Components.md'
        - '3-3 Context': 'react-official-zh/3-3 Context.md'
        - '3-4 错误边界': 'react-official-zh/3-4 错误边界.md'
        - '3-5 Refs 转发': 'react-official-zh/3-5 Refs 转发.md'
        - '3-6 Fragments': 'react-official-zh/3-6 Fragments.md'
        - '3-7 高阶组件': 'react-official-zh/3-7 高阶组件.md'
        - '3-8 与第三方库协同': 'react-official-zh/3-8 与第三方库协同.md'
        - '3-9 深入 JSX': 'react-official-zh/3-9 深入 JSX.md'
        - '4-1 React 顶层 API': 'react-official-zh/4-1 React 顶层 API.md'
        - '4-10 React 术语词汇表': 'react-official-zh/4-10 React 术语词汇表.md'
        - '4-2 React.Component': 'react-official-zh/4-2 React.Component.md'
        - '4-3 ReactDOM': 'react-official-zh/4-3 ReactDOM.md'
        - '4-4 ReactDOMServer': 'react-official-zh/4-4 ReactDOMServer.md'
        - '4-5 DOM 元素': 'react-official-zh/4-5 DOM 元素.md'
        - '4-6 合成事件': 'react-official-zh/4-6 合成事件.md'
        - '4-7 Test Utilities': 'react-official-zh/4-7 Test Utilities.md'
        - '4-8 Test Renderer': 'react-official-zh/4-8 Test Renderer.md'
        - '4-9 JavaScript 环境要求': 'react-official-zh/4-9 JavaScript 环境要求.md'
        - '5-1 Hook 简介': 'react-official-zh/5-1 Hook 简介.md'
        - '5-2 Hook 概览': 'react-official-zh/5-2 Hook 概览.md'
        - '5-3 使用 State Hook': 'react-official-zh/5-3 使用 State Hook.md'
        - '5-4 使用 Effect Hook': 'react-official-zh/5-4 使用 Effect Hook.md'
        - '5-5 Hook 规则': 'react-official-zh/5-5 Hook 规则.md'
        - '5-6 自定义 Hook': 'react-official-zh/5-6 自定义 Hook.md'
        - '5-7 Hook API 索引': 'react-official-zh/5-7 Hook API 索引.md'
        - '5-8 Hooks FAQ': 'react-official-zh/5-8 Hooks FAQ.md'
        - '6-1 测试概览': 'react-official-zh/6-1 测试概览.md'
        - '6-2 测试技巧': 'react-official-zh/6-2 测试技巧.md'
        - '6-3 测试环境': 'react-official-zh/6-3 测试环境.md'
        - '7-1 AJAX and APIs': 'react-official-zh/7-1 AJAX and APIs.md'
        - '7-2 Babel，JSX 及构建过程': 'react-official-zh/7-2 Babel，JSX 及构建过程.md'
        - '7-3 传递函数给组件': 'react-official-zh/7-3 传递函数给组件.md'
        - '7-4 组件状态': 'react-official-zh/7-4 组件状态.md'
        - '7-5 样式与 CSS': 'react-official-zh/7-5 样式与 CSS.md'
        - '7-6 项目文件结构': 'react-official-zh/7-6 项目文件结构.md'
        - '7-7 Virtual DOM 及内核': 'react-official-zh/7-7 Virtual DOM 及内核.md'
        - 'readme': 'react-official-zh/readme.md'
        #   - ant-design/08-样式按需加载.md
        #   - ant-design/09-组件使用.md
        #   - css/Bilibili-模糊实现效果分析-css-filter.md
        #   - git/如何向开源社区提问题.md
        #   - git/如何向开源项目提交无法解答的问题.md
        #   - git/如何有效地报告 Bug.md
        #   - note/network-note.md
        #   - react/react-dnd/官方英文文档/01-readme.md
        #   - react/react-dnd/官方英文文档/02-quickstart.md
        #   - react/react-dnd/官方英文文档/03-Overview.md
        #   - react/react-dnd/官方英文文档/API.md
        #   - react/react-dnd/官方英文文档/React DnD.md
        #   - react/react-dnd/官方英文文档/Testing.md
        #   - react/react-dnd/官方英文文档/Tutorial.md
        #   - react/react-dnd/官方英文文档/react-dnd-DragLayer.md
        #   - react/react-dnd/官方英文文档/react-dnd-DragSource.md
        #   - react/react-dnd/官方英文文档/react-dnd-DropTarget.md
        #   - third-part-lib/294-crypto-js.md
        #   - third-part-lib/005-axios/React使用axios进行ajax操作.md
        #   - third-part-lib/005-axios/react-axios.md
        #   - third-part-lib/005-axios/readme.md
