name: SeaTable Test CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: apt install
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y libevent-dev libcurl4-openssl-dev libglib2.0-dev
          sudo apt-get install -y uuid-dev intltool libsqlite3-dev build-essential
          sudo apt-get install -y libarchive-dev libtool libjansson-dev valac
          sudo apt-get install -y libfuse-dev cmake re2c flex sqlite3
          sudo apt-get install -y libssl-dev libldap2-dev libonig-dev
          sudo apt-get install -y libxml2 libxml2-dev

      - name: clone and build
        run: |
          git clone --depth=1 --branch=master git://github.com/haiwen/seafile-test-deploy /tmp/seafile-test-deploy
          cd /tmp/seafile-test-deploy && git fetch origin python3:python3 && git checkout python3
          ./bootstrap.sh

      - name: clone and init dtable-web
        run: |
          export CCNET_CONF_DIR=/tmp/ccnet SEAFILE_CONF_DIR=/tmp/seafile-data
          ./test/init-dtable-web.sh

      - name: run npm test
        run: |
          cd $GITHUB_WORKSPACE
          export LOG_DIR=$GITHUB_WORKSPACE DTABLE_SERVER_CONFIG=test/test-config.json
          npm install
          npm run build
          npm run test-api
          npm run test-modal
