site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python
    palette:
        primary: "deep orange"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# minify: https://github.com/byrnereese/mkdocs-minify-plugin
plugins:
    - search # necessary for search to work
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
        js_files:
            - /js/history.js
            - /js/baidu-statistics.js

extra:
  search:
    language: 'jp'

extra_javascript:
    - 'js/baidu-statistics.min.js'
    - 'js/history.min.js'

# Page tree
nav:
    - 介绍: 'index.md'
    - 数据库:
        - '01-redis': 'backend-sql/01-redis.md'
        - '02-阿里云MySQL入门': 'backend-sql/02-阿里云MySQL入门.md'
        - '03-数据库概念': 'backend-sql/03-数据库概念.md'
        - '04-单点登录SSO': 'backend-sql/04-单点登录SSO.md'
        - '05-websocket': 'backend-sql/05-websocket.md'
        - '06-socket-io': 'backend-sql/06-socket-io.md'
        - '07-SQLite-API-Python': 'backend-sql/07-SQLite-API-Python.md'
        - '20-深入MySQL数据库': 'backend-sql/20-深入MySQL数据库.md'
        - '21-Mac-安装-python-mysql-报错': 'backend-sql/21-Mac-安装-python-mysql-报错.md'
        - '22-Python操作 MySQL数据库': 'backend-sql/22-Python操作 MySQL数据库.md'
        - '23-Mac pip install mysql-python': 'backend-sql/23-Mac pip install mysql-python.md'
        - '24-node连接Mysql报错': 'backend-sql/24-node连接Mysql报错.md'
    - NodeJS:
        - '01-Node.js 教程': 'nodejs/01-Node.js 教程.md'
        - '02-Node.js 安装配置': 'nodejs/02-Node.js 安装配置.md'
        - '03-Node.js 创建第一个应用': 'nodejs/03-Node.js 创建第一个应用.md'
        - '04-NPM 使用介绍': 'nodejs/04-NPM 使用介绍.md'
        - '05-Node.js REPL(交互式解释器)': 'nodejs/05-Node.js REPL(交互式解释器).md'
        - '06-Node.js 回调函数': 'nodejs/06-Node.js 回调函数.md'
        - '07-Node.js 事件循环': 'nodejs/07-Node.js 事件循环.md'
        - '08-Node.js EventEmitter': 'nodejs/08-Node.js EventEmitter.md'
        - '09-Node.js Buffer(缓冲区)': 'nodejs/09-Node.js Buffer(缓冲区).md'
        - '10-Node.js Stream(流)': 'nodejs/10-Node.js Stream(流).md'
        - '11-Node.js模块系统': 'nodejs/11-Node.js模块系统.md'
        - '12-Node.js 函数': 'nodejs/12-Node.js 函数.md'
        - '13-Node.js 路由': 'nodejs/13-Node.js 路由.md'
        - '14-Node.js 全局对象': 'nodejs/14-Node.js 全局对象.md'
        - '15-Node.js 常用工具': 'nodejs/15-Node.js 常用工具.md'
        - '16-Node.js 文件系统': 'nodejs/16-Node.js 文件系统.md'
        - '17-Node.js GETPOST请求': 'nodejs/17-Node.js GETPOST请求.md'
        - '18-Node.js 工具模块': 'nodejs/18-Node.js 工具模块.md'
        - '19-Node.js Web 模块': 'nodejs/19-Node.js Web 模块.md'
        - '20-Node.js Express 框架': 'nodejs/20-Node.js Express 框架.md'
        - '21-Node.js RESTful API': 'nodejs/21-Node.js RESTful API.md'
        - '22-Node.js 多进程': 'nodejs/22-Node.js 多进程.md'
        - '23-Node.js JXcore 打包': 'nodejs/23-Node.js JXcore 打包.md'
        - '24-Node.js 连接 MySQL': 'nodejs/24-Node.js 连接 MySQL.md'
        - '25-Node.js 连接 MongoDB': 'nodejs/25-Node.js 连接 MongoDB.md'
        - 'Node-LDAP': 'nodejs/Node-LDAP.md'
        - 'Node.js-fs文档': 'nodejs/Node.js-fs文档.md'
        - 'Node.js-path': 'nodejs/Node.js-path.md'
        - 'Node.js-全局变量': 'nodejs/Node.js-全局变量.md'
        - 'Node.js使用Nodemailer发送邮件': 'nodejs/Node.js使用Nodemailer发送邮件.md'
        - 'NodeJS': 'nodejs/NodeJS.md'
        - 'fs.createReadStream': 'nodejs/fs.createReadStream.md'
        - 'node-debug': 'nodejs/node-debug.md'
        - 'nodeJS+mysql+连接池': 'nodejs/nodeJS+mysql+连接池.md'
        - 'README': 'nodejs/nodeJS高频词/README.md'
        - 'node定时器': 'nodejs/node定时器.md'
        - '使用nodejs连接mysql数据库实现增删改查': 'nodejs/使用nodejs连接mysql数据库实现增删改查.md'
        - '命令行的nodeJS': 'nodejs/命令行的nodeJS.md'
        - '廖雪峰 NodeJS': 'nodejs/廖雪峰 NodeJS.md'
        - '谈谈Node中的常见概念': 'nodejs/谈谈Node中的常见概念.md'
    - python:
        - '01-Detect mobile devices with Django and Python 3': 'python/01-Detect mobile devices with Django and Python 3.md'
        - '02-pandas': 'python/02-pandas.md'
        - '03-搭建python3开发环境': 'python/03-搭建python3开发环境.md'
        - '04-matplotlib': 'python/04-matplotlib.md'
        - '05-numpy': 'python/05-numpy.md'
        - '06-docker-basic-use': 'python/06-docker-basic-use.md'
        - '07-seaborn': 'python/07-seaborn.md'
        - '08-黑马程序员-linux基础': 'python/08-黑马程序员-linux基础.md'
        - '09-Python3 序列解包': 'python/09-Python3 序列解包.md'
        - '10-UnicodeDecodeError utf8 codec cant decode invalid start byte': 'python/10-UnicodeDecodeError utf8 codec cant decode invalid start byte.md'
        - '11-黑马程序员-python基础': 'python/11-黑马程序员-python基础.md'
        - 'Docker 入门教程': 'python/Docker 入门教程.md'
        - 'Docker 微服务教程': 'python/Docker 微服务教程.md'
        - 'Docker笔记': 'python/Docker笔记.md'
        - 'Nginx 容器教程': 'python/Nginx 容器教程.md'
        - 'Python3 多线程': 'python/Python3 多线程.md'
        - 'no-Django入门': 'python/no-Django入门.md'
        - 'no-django 常见问题': 'python/no-django 常见问题.md'
        - 'no-django-basic': 'python/no-django-basic.md'
        - 'no-flask-basic': 'python/no-flask-basic.md'
        - 'no-flask网易云课堂笔记': 'python/no-flask网易云课堂笔记.md'
        - 'python3-subporcess 子进程管理模块': 'python/python3-subporcess 子进程管理模块.md'
        - 'Simple Minecraft-inspired program using Python': 'python/Simple Minecraft-inspired program using Python and Pyglet.md'        
    - ruby:
        - 'no-install-ruby': 'ruby/no-install-ruby.md'
        - 'no-jekyll-basic': 'ruby/no-jekyll-basic.md'
        - 'no-jekyll-install': 'ruby/no-jekyll-install.md'
        - 'no-ruby-readme': 'ruby/no-ruby-readme.md'
