site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - bash
    - javascript
    - python
  palette:
    primary: "deep orange"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# minify: https://github.com/byrnereese/mkdocs-minify-plugin
# use this plugin will increase build time and decrease browser render time
plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - git-authors
  - git-committers
  - minify:
      minify_html: false
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - /js/history.js
        - /js/baidu-statistics.js

extra:
  search:
    language: "jp"

extra_javascript:
  - "js/baidu-statistics.min.js"
  - "js/history.min.js"

# Page tree
nav:
  - 介绍: "index.md"
  - 数据库:
    - '01-redis': 'backend-sql/01-redis.md'
    - '02-阿里云MySQL入门': 'backend-sql/02-阿里云MySQL入门.md'
    - '03-数据库概念': 'backend-sql/03-数据库概念.md'
    - '04-单点登录SSO': 'backend-sql/04-单点登录SSO.md'
    - '05-websocket': 'backend-sql/05-websocket.md'
    - '06-socket-io': 'backend-sql/06-socket-io.md'
    - '07-SQLite-API-Python': 'backend-sql/07-SQLite-API-Python.md'
    - '08-进程和线程': 'backend-sql/08-进程和线程.md'
    - '09-进程与线程的一个简单解释': 'backend-sql/09-进程与线程的一个简单解释.md'
    - '10-Mysql视图': 'backend-sql/10-Mysql视图.md'
    - '20-深入MySQL数据库': 'backend-sql/20-深入MySQL数据库.md'
    - '21-Mac-安装-python-mysql-报错': 'backend-sql/21-Mac-安装-python-mysql-报错.md'
    - '22-Python操作 MySQL数据库': 'backend-sql/22-Python操作 MySQL数据库.md'
    - '23-Mac pip install mysql-python': 'backend-sql/23-Mac pip install mysql-python.md'
    - '24-node连接Mysql报错': 'backend-sql/24-node连接Mysql报错.md'
    - '25-mysql支持emoji表情储存': 'backend-sql/25-mysql支持emoji表情储存.md'
    - '26-数据库多表链接': 'backend-sql/26-数据库多表链接.md'

  - NodeJS:
      - 'Node 下 LDAP 实现': 'nodejs/Node 下 LDAP 实现.md'
      - 'Node-LDAP': 'nodejs/Node-LDAP.md'
      - 'Node.js-path': 'nodejs/Node.js-path.md'
      - 'Node.js-全局变量': 'nodejs/Node.js-全局变量.md'
      - 'Node.js使用Nodemailer发送邮件': 'nodejs/Node.js使用Nodemailer发送邮件.md'
      - 'NodeJS中进程和线程': 'nodejs/NodeJS中进程和线程.md'
      - 'fs.createReadStream': 'nodejs/fs.createReadStream.md'
      - 'node-debug': 'nodejs/node-debug.md'
      - 'nodeJS+mysql+连接池': 'nodejs/nodeJS+mysql+连接池.md'
      - 'README': 'nodejs/nodeJS高频词/README.md'
      - 'node定时器': 'nodejs/node定时器.md'
      - '使用nodejs连接mysql数据库实现增删改查': 'nodejs/使用nodejs连接mysql数据库实现增删改查.md'
      - '命令行的nodeJS': 'nodejs/命令行的nodeJS.md'
      - '廖雪峰 NodeJS': 'nodejs/廖雪峰 NodeJS.md'
      - '谈谈Node中的常见概念': 'nodejs/谈谈Node中的常见概念.md'
  - 服务器:
      - 'GraphQL vs REST API 架构': 'server/GraphQL vs REST API 架构.md'
      - 'LAMP平台的部署及应用': 'server/LAMP平台的部署及应用.md'
      - 'Linux 安装 MySQL数据库系统': 'server/Linux 安装 MySQL数据库系统.md'
      - 'Linux如何搭建Apache网站服务': 'server/Linux如何搭建Apache网站服务.md'
      - 'Mac上搭建nginx教程': 'server/Mac上搭建nginx教程.md'
      - 'RESTful API 设计指南': 'server/RESTful API 设计指南.md'
      - 'SSH原理与运用-远程登录': 'server/SSH原理与运用-远程登录.md'
      - 'bzip2': 'server/bzip2.md'
      - 'readme': 'server/docker-compose-demo/readme.md'
      - 'ipad 使用小技巧': 'server/ipad 使用小技巧.md'
      - 'nginx': 'server/nginx.md'
      - '为什么我使用 GraphQL 而放弃 REST': 'server/为什么我使用 GraphQL 而放弃 REST.md'
      - '从购买服务器到网站搭建成功教程': 'server/从购买服务器到网站搭建成功教程.md'
      - '分布式和集群': 'server/分布式和集群.md'
      - '计算机组成原理知识': 'server/计算机组成原理知识.md'
  - 网络:
      - '2017-12-19-travis-ci-tutorial': 'network/2017-12-19-travis-ci-tutorial.md'
      - '2018-07-04-indexeddb': 'network/2018-07-04-indexeddb.md'
      - '2018-07-09-web-worker': 'network/2018-07-09-web-worker.md'
      - 'CDN': 'network/CDN.md'
      - 'Nginx在应用程序中的作用': 'network/Nginx在应用程序中的作用.md'
      - 'Token': 'network/Token.md'
      - 'Visual Studio Code必备插件': 'network/Visual Studio Code必备插件.md'
      - 'chrome': 'network/chrome.md'
      - 'ddos': 'network/ddos.md'
      - 'dns': 'network/dns.md'
      - 'http': 'network/http.md'
      - 'mac': 'network/mac.md'
      - 'nginx': 'network/nginx.md'
      - 'python-socket': 'network/python-socket.md'
      - 'serviceworker': 'network/serviceworker.md'
      - 'ssl协议': 'network/ssl协议.md'
      - '一个 TCP 连接上面能发多少个 HTTP 请求': 'network/一个 TCP 连接上面能发多少个 HTTP 请求.md'
      - '基本网络安全': 'network/基本网络安全.md'
      - '虚拟机': 'network/虚拟机.md'
      - '计算机网络基础知识': 'network/计算机网络基础知识.md'
      - '跨域': 'network/跨域.md'
      - '跨域2': 'network/跨域2.md'
  - 其他:
      - "express 入门笔记": "express/express 入门笔记.md"
