site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python
    palette:
        primary: "orange"

extra_javascript:
    - 'js/baidu-statistics.min.js'
    - 'js/history.min.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# minify: https://github.com/byrnereese/mkdocs-minify-plugin
# use this plugin will increase build time and decrease browser render time
plugins:
    - search # necessary for search to work
    - minify:
        minify_html: false
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
        js_files:
            - /js/history.js
            - /js/baidu-statistics.js

extra:
  search:
    language: 'jp'

# Page tree
nav:
    - About:
        - '关于': 'index.md'
        - 'changelog': 'changelog.md'
    - 笔记:
        - 'algre-note': 'note/algre-note.md'
        - 'frontend-note': 'note/frontend-note.md'
        - 'network-note': 'note/network-note.md'
        - 'other-note': 'note/other-note.md'
        - 'think-note': 'note/think-note.md'
        - '2021年度总结': 'note/2021年度总结.md'
        - '2022年度总结': 'note/2022年度总结.md'
        - '2022年前端新技术汇总': 'note/2022年前端新技术汇总.md'
        - 'log': 'note/log.md'
    - 金融理财:
        - '2019-时事经济思考': 'economy/2019-时事经济思考.md'
        - '2021-时事经济思考': 'economy/2021-时事经济思考.md'
        - '2022-时事经济思考': 'economy/2022-时事经济思考.md'
        - '2023-时事经济思考': 'economy/2023-时事经济思考.md'
        - 'My Top 10 Money Rules': 'economy/My Top 10 Money Rules.md'
        - 'The art of Execution 执行力的艺术': 'economy/The art of Execution 执行力的艺术.md'
        - 'Who Wants to Be a Millionaire': 'economy/Who Wants to Be a Millionaire.md'
        - '中国的房价会怎么收场': 'economy/中国的房价会怎么收场.md'
        - '中国经济的数字逻辑': 'economy/中国经济的数字逻辑.md'
        - '中国经济的转变': 'economy/中国经济的转变.md'
        - '人人都能懂的宏观经济': 'economy/人人都能懂的宏观经济.md'
        - '关于房地产的一些随意的狂想': 'economy/关于房地产的一些随意的狂想.md'
        - '四个财富水池': 'economy/四个财富水池.md'
        - '基金从基础到实践': 'economy/基金从基础到实践.md'
        - '基金投资法': 'economy/基金投资法.md'
        - '小狗钱钱': 'economy/小狗钱钱.md'
        - '经典书籍推荐': 'economy/经典书籍推荐.md'
        - '致当下奋斗的青年': 'economy/致当下奋斗的青年.md'
        - '降准预期下的货币供应问题': 'economy/降准预期下的货币供应问题.md'
    - 人生思考:
        - '掘金技术大会': 'other/掘金技术大会.md'
        - '40退休': 'other/40退休.md'
        - 'Interview with Ryan Dahl Creator of Node.js': 'other/Interview with Ryan Dahl Creator of Node.js.md'
        - 'Less is more': 'other/Less is more.md'
        - 'Poor-and-busy': 'other/Poor-and-busy.md'
        - 'Reflections on Pre-Tirement': 'other/Reflections on Pre-Tirement.md'
        - 'Tips On Prioritizing Tech Debt In A Healthy Way': 'other/Tips On Prioritizing Tech Debt In A Healthy Way.md'
        - 'b计划': 'other/b计划.md'
        - 'index': 'other/index.md'
        - '专业教育的兴起': 'other/专业教育的兴起.md'
        - '个人选择': 'other/个人选择.md'
        - '人生真相': 'other/人生真相.md'
        - '从梦想倒逼计划': 'other/从梦想倒逼计划.md'
        - '任正非的管理思想': 'other/任正非的管理思想.md'
        - '保持精力充沛': 'other/保持精力充沛.md'
        - '元宇宙-摘录与读后感': 'other/元宇宙-摘录与读后感.md'
        - '制定好的计划总是坚持不下去怎么办': 'other/制定好的计划总是坚持不下去怎么办.md'
        - '前端如何高效的与后端协作开发': 'other/前端如何高效的与后端协作开发.md'
        - '大学教育和网络文凭': 'other/大学教育和网络文凭.md'
        - '如何变得强大': 'other/如何变得强大.md'
        - '如何描述自己的工作': 'other/如何描述自己的工作.md'
        - '工业文明对于社会的冲击': 'other/工业文明对于社会的冲击.md'
        - '思维导图到深度学习': 'other/思维导图到深度学习.md'
        - '技术和稳定的工作': 'other/技术和稳定的工作.md'
        - '改善睡眠小技巧': 'other/改善睡眠小技巧.md'
        - '熵增': 'other/熵增.md'
        - '硕士学位的贬值': 'other/硕士学位的贬值.md'
        - '詹宏志读书': 'other/詹宏志读书.md'
        - '骡子和人生': 'other/骡子和人生.md'
        - 'Create A Video Streaming App Features': 'other/Create A Video Streaming App Features.md'
        - '常用网站和友情链接': 'other/常用网站和友情链接.md'
        - '提升工作效率': 'other/提升工作效率.md'
        - '程序员如何利用周末提高.md': 'other/程序员如何利用周末提高.md'
        - '高效读源码': 'other/高效读源码.md'
