site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python
    palette:
        # primary: "red"
        # primary: "deep orange"
        primary: "orange"
        # primary: "blue"
        # primary: "pirple"
        # primary: "green"

extra_javascript:
    - 'js/baidu-statistics.min.js'
    - 'js/history.min.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# minify: https://github.com/byrnereese/mkdocs-minify-plugin
plugins:
    - search # necessary for search to work
    - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
        js_files:
            - /js/history.js
            - /js/baidu-statistics.js

extra:
  search:
    language: 'jp'

# Page tree
nav:
    - About:        
        - 'changelog': 'changelog.md'
        - 'github-projects': 'github-projects.md'
        - 'index': 'index.md'
        - 'log': 'log.md'
        - 'mkdocs': 'mkdocs.md'
        - 'thought': 'thought.md'
    - 金融理财:
        - 'My Top 10 Money Rules': 'economy/My Top 10 Money Rules.md'
        - 'The art of Execution 执行力的艺术': 'economy/The art of Execution 执行力的艺术.md'
        - 'Who Wants to Be a Millionaire': 'economy/Who Wants to Be a Millionaire.md'
        - '中国的房价会怎么收场': 'economy/中国的房价会怎么收场.md'
        - '中国经济的转变': 'economy/中国经济的转变.md'
        - '人人都能懂的宏观经济': 'economy/人人都能懂的宏观经济.md'
        - '关于房地产的一些随意的狂想': 'economy/关于房地产的一些随意的狂想.md'
        - '四个财富水池': 'economy/四个财富水池.md'
        - '基金从基础到实践': 'economy/基金从基础到实践.md'
        - '基金投资法': 'economy/基金投资法.md'
        - '小狗钱钱': 'economy/小狗钱钱.md'
        - '时事经济思考': 'economy/时事经济思考.md'
        - '经典书籍推荐': 'economy/经典书籍推荐.md'
        - '股市入门': 'economy/股市入门.md'
        - '致当下奋斗的青年': 'economy/致当下奋斗的青年.md'
        - '降准预期下的货币供应问题': 'economy/降准预期下的货币供应问题.md'
    - 人生思考:
        - '40退休': 'other/40退休.md'
        - '426 Upgrade Required 报错': 'other/426 Upgrade Required 报错.md'
        - 'Interview with Ryan Dahl Creator of Node.js': 'other/Interview with Ryan Dahl Creator of Node.js.md'
        - 'Nodejs创造者Ryan Dahl专访': 'other/Nodejs创造者Ryan Dahl专访.md'
        - 'Poor-and-busy': 'other/Poor-and-busy.md'
        - 'Reflections on Pre-Tirement': 'other/Reflections on Pre-Tirement.md'
        - 'UV和PV的定义': 'other/UV和PV的定义.md'
        - 'Visual Studio Code 功能插件和设置': 'other/Visual Studio Code 功能插件和设置.md'
        - 'b计划': 'other/b计划.md'
        - 'index': 'other/index.md'
        - '专业教育的兴起': 'other/专业教育的兴起.md'
        - '个人选择': 'other/个人选择.md'
        - '丹尼斯与Unix': 'other/丹尼斯与Unix.md'
        - '人生真相': 'other/人生真相.md'
        - '任正非的管理思想': 'other/任正非的管理思想.md'
        - '大四程序员选择去大公司还是小公司': 'other/大四程序员选择去大公司还是小公司.md'
        - '大学教育和网络文凭': 'other/大学教育和网络文凭.md'
        - '如何变得强大': 'other/如何变得强大.md'
        - '如何描述自己的工作': 'other/如何描述自己的工作.md'
        - '工业文明对于社会的冲击': 'other/工业文明对于社会的冲击.md'
        - '思维导图到深度学习': 'other/思维导图到深度学习.md'
        - '技术和稳定的工作': 'other/技术和稳定的工作.md'
        - '清理Mac磁盘文件': 'other/清理Mac磁盘文件.md'
        - '熵增': 'other/熵增.md'
        - '硕士学位的贬值': 'other/硕士学位的贬值.md'
        - '詹宏志读书': 'other/詹宏志读书.md'
        - '阿里巴巴2019技术展望': 'other/阿里巴巴2019技术展望.md'
        - '骡子和人生': 'other/骡子和人生.md'
    - 数学算法:
        - 'Hire for slope not Y Intercept': 'math/Hire for slope not Y Intercept.md'
        - '期望-方差-协方差-相关系数': 'math/期望-方差-协方差-相关系数.md'
        - '正态分布和对数正态分布': 'math/正态分布和对数正态分布.md'
        - '蒙特卡罗方法入门': 'math/蒙特卡罗方法入门.md'
    - 课外读物:
        - 'readme': 'Jane/readme.md'
        - '00-Biography': 'Jane/00-Biography.md'
        - '00-Preface': 'Jane/00-Preface.md'
        - '01-Chapter 1': 'Jane/01-Chapter 1.md'
        - '02-Chapter 2': 'Jane/02-Chapter 2.md'
        - '03-Chapter 3': 'Jane/03-Chapter 3.md'
        - '04-Chapter 4': 'Jane/04-Chapter 4.md'
        - '05-Chapter 5': 'Jane/05-Chapter 5.md'
        - '06-Chapter 6': 'Jane/06-Chapter 6.md'
        - '07-Chapter 7': 'Jane/07-Chapter 7.md'
        - '08-Chapter 8': 'Jane/08-Chapter 8.md'
        - '09-Chapter 9': 'Jane/09-Chapter 9.md'
        - '10-Chapter 10': 'Jane/10-Chapter 10.md'
        - 'Jane Eyre': 'Jane/Jane Eyre.md'
    - 其他日志:
        - 'alibaba-ice': 'old/alibaba-ice.md'
        - 'alibaba-open-source-instructions': 'old/alibaba-open-source-instructions.md'
        - 'browser-sync': 'old/browser-sync.md'
        - 'ice-instructions': 'old/ice-instructions.md'
        - 'mui-instructions': 'old/mui-instructions.md'
        - 'showdoc_saying': 'old/showdoc_saying.md'
        - 'vue-state-management': 'old/vue-state-management.md'
        - 'vue_responsive_principle': 'old/vue_responsive_principle.md'
        - 'vue_websocket': 'old/vue_websocket.md'
        - 'wechat-choose-geolocation': 'old/wechat-choose-geolocation.md'
