site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python
    palette:
        primary: "orange"

extra_javascript:
    - 'js/baidu-statistics.min.js'
    - 'js/history.min.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# minify: https://github.com/byrnereese/mkdocs-minify-plugin
# use this plugin will increase build time and decrease browser render time
plugins:
    - search # necessary for search to work
    - git-revision-date-localized
    - git-authors
    - git-committers
    - minify:
        minify_html: false
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
        js_files:
            - /js/history.js
            - /js/baidu-statistics.js

extra:
  search:
    language: 'jp'

# Page tree
nav:

    - AI:
        - '01-Monica': 'AI/01-Monica.md'
        - '02 chatGPT——AI 发展存在的问题': 'AI/02 chatGPT——AI 发展存在的问题.md'
        - '全面深入了解大模型': 'AI/全面深入了解大模型.md'
        - 'changelog': 'changelog.md'

    - class-note:
        - 'AI 大模型-笔记': 'class-note/AI 大模型-笔记.md'
        - 'JS 红宝书-笔记': 'class-note/JS 红宝书-笔记.md'
        - 'MYSQL-笔记': 'class-note/MYSQL-笔记.md'
        - 'UI设计-笔记1': 'class-note/UI设计-笔记1.md'
        - 'UI设计-笔记2': 'class-note/UI设计-笔记2.md'
        - '机器学习入门-笔记': 'class-note/机器学习入门-笔记.md'
        - '稀土开发者大会-笔记': 'class-note/稀土开发者大会-笔记.md'
        - '计算机组成原理-笔记': 'class-note/计算机组成原理-笔记.md'

    - economy:
        - '2019-时事经济思考': 'economy/2019-时事经济思考.md'
        - '2021-时事经济思考': 'economy/2021-时事经济思考.md'
        - '2022-时事经济思考': 'economy/2022-时事经济思考.md'
        - '2023-08 宏观经济分析': 'economy/2023-08 宏观经济分析.md'
        - '2023-时事经济思考': 'economy/2023-时事经济思考.md'
        - '2023会议记录': 'economy/2023会议记录.md'
        - '2024-06热点分析': 'economy/2024-06热点分析.md'
        - '2024-金融经济分析': 'economy/2024-金融经济分析.md'
        - 'My Top 10 Money Rules': 'economy/My Top 10 Money Rules.md'
        - 'TIPS TO BECOME A MILLIONAIRE IF YOU DESERVE TO BE': 'economy/TIPS TO BECOME A MILLIONAIRE IF YOU DESERVE TO BE.md'
        - 'The art of Execution 执行力的艺术': 'economy/The art of Execution 执行力的艺术.md'
        - 'Who Wants to Be a Millionaire': 'economy/Who Wants to Be a Millionaire.md'
        - '中国的房价会怎么收场': 'economy/中国的房价会怎么收场.md'
        - '中国经济的数字逻辑': 'economy/中国经济的数字逻辑.md'
        - '中国经济的转变': 'economy/中国经济的转变.md'
        - '人人都能懂的宏观经济': 'economy/人人都能懂的宏观经济.md'
        - '关于房地产的一些随意的狂想': 'economy/关于房地产的一些随意的狂想.md'
        - '四个财富水池': 'economy/四个财富水池.md'
        - '基金从基础到实践': 'economy/基金从基础到实践.md'
        - '基金基础知识-笔记': 'economy/基金基础知识-笔记.md'
        - '基金投资法': 'economy/基金投资法.md'
        - '基金法规-笔记': 'economy/基金法规-笔记.md'
        - '小狗钱钱': 'economy/小狗钱钱.md'
        - '小狗钱钱2': 'economy/小狗钱钱2.md'
        - '常用基金名词': 'economy/常用基金名词.md'
        - '经典书籍推荐': 'economy/经典书籍推荐.md'
        - '给年轻人的极简金融课程': 'economy/给年轻人的极简金融课程.md'
        - '致当下奋斗的青年': 'economy/致当下奋斗的青年.md'
        - '财务自由之路': 'economy/财务自由之路.md'
        - '降准预期下的货币供应问题': 'economy/降准预期下的货币供应问题.md'
        - 'index': 'index.md'

    - new:
        - '2021年度总结': 'new/2021年度总结.md'
        - '2022年度总结': 'new/2022年度总结.md'
        - 'github项目介绍': 'new/github项目介绍.md'
        - 'log': 'new/log.md'
        - '人生思考-笔记': 'new/人生思考-笔记.md'
        - '算法感悟': 'new/算法感悟.md'

    - note:
        - 'BOM-笔记': 'note/BOM-笔记.md'
        - 'Go-笔记': 'note/Go-笔记.md'
        - 'H5+CSS-笔记': 'note/H5+CSS-笔记.md'
        - 'JS-笔记': 'note/JS-笔记.md'
        - 'JS第三方库-笔记': 'note/JS第三方库-笔记.md'
        - 'Linux-笔记': 'note/Linux-笔记.md'
        - 'Python-笔记': 'note/Python-笔记.md'
        - 'React-笔记': 'note/React-笔记.md'
        - 'VUE 相关第三方库-笔记': 'note/VUE 相关第三方库-笔记.md'
        - 'nodejs-笔记': 'note/nodejs-笔记.md'
        - 'redux-笔记': 'note/redux-笔记.md'
        - '产品-笔记': 'note/产品-笔记.md'
        - '奇技淫巧-笔记': 'note/奇技淫巧-笔记.md'
        - '工程化-笔记': 'note/工程化-笔记.md'
        - '数据库-笔记': 'note/数据库-笔记.md'
        - '服务器-笔记': 'note/服务器-笔记.md'
        - '第三方库-笔记': 'note/第三方库-笔记.md'
        - '算法-笔记': 'note/算法-笔记.md'
        - '计算机网络-笔记': 'note/计算机网络-笔记.md'
        - '运营-笔记': 'note/运营-笔记.md'
        - '高频单词表-笔记': 'note/高频单词表-笔记.md'

    - other:
        - '40退休': 'other/40退休.md'
        - 'Create A Video Streaming App Features': 'other/Create A Video Streaming App Features.md'
        - 'Interview with Ryan Dahl Creator of Node.js': 'other/Interview with Ryan Dahl Creator of Node.js.md'
        - 'Less is more': 'other/Less is more.md'
        - 'Poor-and-busy': 'other/Poor-and-busy.md'
        - 'Reflections on Pre-Tirement': 'other/Reflections on Pre-Tirement.md'
        - 'Tips On Prioritizing Tech Debt In A Healthy Way': 'other/Tips On Prioritizing Tech Debt In A Healthy Way.md'
        - 'b计划': 'other/b计划.md'
        - 'index': 'other/index.md'
        - '专业教育的兴起': 'other/专业教育的兴起.md'
        - '个人选择': 'other/个人选择.md'
        - '人生真相': 'other/人生真相.md'
        - '从梦想倒逼计划': 'other/从梦想倒逼计划.md'
        - '任正非的管理思想': 'other/任正非的管理思想.md'
        - '你为什么卸载推荐算法软件': 'other/你为什么卸载推荐算法软件.md'
        - '保持精力充沛': 'other/保持精力充沛.md'
        - '元宇宙-摘录与读后感': 'other/元宇宙-摘录与读后感.md'
        - '创业后和公司上班': 'other/创业后和公司上班.md'
        - '创业者需要知道的50句话': 'other/创业者需要知道的50句话.md'
        - '制定好的计划总是坚持不下去怎么办': 'other/制定好的计划总是坚持不下去怎么办.md'
        - '前端如何高效的与后端协作开发': 'other/前端如何高效的与后端协作开发.md'
        - '大学教育和网络文凭': 'other/大学教育和网络文凭.md'
        - '如何变得强大': 'other/如何变得强大.md'
        - '如何描述自己的工作': 'other/如何描述自己的工作.md'
        - '工业文明对于社会的冲击': 'other/工业文明对于社会的冲击.md'
        - '常用网站和友情链接': 'other/常用网站和友情链接.md'
        - '思维导图到深度学习': 'other/思维导图到深度学习.md'
        - '技术和稳定的工作': 'other/技术和稳定的工作.md'
        - '掘金技术大会': 'other/掘金技术大会.md'
        - '提升工作效率': 'other/提升工作效率.md'
        - '改善睡眠小技巧': 'other/改善睡眠小技巧.md'
        - '浅谈知识体系': 'other/浅谈知识体系.md'
        - '熵增': 'other/熵增.md'
        - '硕士学位的贬值': 'other/硕士学位的贬值.md'
        - '程序员如何利用周末提高': 'other/程序员如何利用周末提高.md'
        - '詹宏志读书': 'other/詹宏志读书.md'
        - '软件工程师的职业建议': 'other/软件工程师的职业建议.md'
        - '通用英语单词': 'other/通用英语单词.md'
        - '骡子和人生': 'other/骡子和人生.md'
        - '高效读源码': 'other/高效读源码.md'
