site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    palette:
        primary: "purple"

# Page tree
nav:
    - 关于:
        - 'index': 'index.md'
    - 前端:
        - 'HTTP': 'HTTP.md'
        - 'UI': 'UI.md'
        - 'basic': 'basic.md'
        - 'react': 'react.md'
        - 'design': 'design.md'
        - 'dot': 'dot.md'
        - 'network': 'network.md'
        - 'others': 'others.md'
        - 'css' : 'css.md'
        - 'future' : 'future.md'
        - 'git' : 'git.md'
