site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
    palette:
        primary: "red"

extra_javascript:
    - 'js/baidu-statistics.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# plugins:
#   - search # necessary for search to work

# extra:
#   search:
#     language: 'jp'

# Page tree
nav:
    - 算法:
        - '说明': 'index.md'
        - '00-练习之前，你需要了解的': 'algre/00-练习之前，你需要了解的.md'
        - '01-反转链表': 'algre/01-反转链表.md'
        - '02-环形链表': 'algre/02-环形链表.md'
        - '03-链表合并': 'algre/03-链表合并.md'
        - '04-求链表中间节点': 'algre/04-求链表中间节点.md'
        - '05-二叉树层序遍历': 'algre/05-二叉树层序遍历.md'
        - '06-无权图 BFS 遍历': 'algre/06-无权图 BFS 遍历.md'
        - '07-实现优先队列': 'algre/07-实现优先队列.md'
        - '08-双端队列及应用': 'algre/08-双端队列及应用.md'
        - '09-栈和队列的相互实现': 'algre/09-栈和队列的相互实现.md'
        - '10-n 数之和': 'algre/10-n 数之和.md'
        - '11-二叉树': 'algre/11-二叉树.md'
        - 'K-means': 'algre/K-means.md'
        - 'K-means聚类算法': 'algre/K-means聚类算法.md'
        - 'LeetCode刷题方法': 'algre/LeetCode刷题方法.md'
        - 'diverce': 'algre/diverce.md'
        - 'double-pointer': 'algre/double-pointer.md'
        - 'in-place': 'algre/in-place.md'
        - 'part-two': 'algre/part-two.md'
        - '二分法': 'algre/二分法.md'
        - '双指针': 'algre/双指针.md'
        - '图算法': 'algre/图算法.md'
        - '字典树': 'algre/字典树.md'
        - '树算法': 'algre/树算法.md'
        - '分治算法': 'algre/分治算法.md'
        - '刷题窍门': 'algre/刷题窍门.md'
        - '原地算法': 'algre/原地算法.md'
        - '排序算法': 'algre/排序算法.md'
        - '数组算法': 'algre/数组算法.md'
        - '贪心算法': 'algre/贪心算法.md'
        - '链表算法': 'algre/链表算法.md'
        - '字符串算法': 'algre/字符串算法.md'
        - '栈队列算法': 'algre/栈队列算法.md'
        - '常见算法思想': 'algre/常见算法思想.md'
    - 刷题:
        - '01 面试题1-(1-30).md': 'interview/01 面试题1-(1-30).md'
        - '02 面试题1-(30-60).md': 'interview/02 面试题1-(30-60).md'
        - '03 面试题1-(60-100).md': 'interview/03 面试题1-(60-100).md'
        - '04 面试题2-比较老.md': 'interview/04 面试题2-比较老.md'
        - '05 面试题5-有答案.md': 'interview/05 面试题5-有答案.md'
        - '06 大厂要求.md': 'interview/06 大厂要求.md'
        - '07 面试题1-(101-136).md': 'interview/07 面试题1-(101-136).md'
        - '08 面试题3-没答案.md': 'interview/08 面试题3-没答案.md'
        - '09 面试题4(全栈).md': 'interview/09 面试题4(全栈).md'
        - '10 HR面试题目-正在做.md': 'interview/10 HR面试题目-正在做.md'
        - '11 豪情大佬日常工作感悟.md': 'interview/11 豪情大佬日常工作感悟.md'
        - '12 知识体系.md': 'interview/12 知识体系.md'
        - '13 facebook 国外面试.md': 'interview/13 facebook 国外面试.md'
        - '14 阿里1-4面面经.md': 'interview/14 阿里1-4面面经.md'
        - '15 JavaScript 基础.md': 'interview/15 JavaScript 基础.md'
        - '16 字节面试.md': 'interview/16 字节面试.md'
        - '17 菜鸟教程面试.md': 'interview/17 菜鸟教程面试.md'
        - '18 前端日常开发必背知识点.md': 'interview/18 前端日常开发必背知识点.md'
        - '19 知乎面试.md': 'interview/19 知乎面试.md'
        - '20 搜狗前端面试题.md': 'interview/20 搜狗前端面试题.md'
