site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
    palette:
        primary: "blue"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# plugins:
#   - search # necessary for search to work

extra_javascript:
    - 'js/baidu-statistics.js'

# extra:
#   search:
#     language: 'jp'

# Page tree
nav:
    - 人生思考:
        - '说明': 'index.md'
        - '40退休': 'other/40退休.md'
        - 'JS 数据结构': 'other/JS 数据结构.md'
        - 'Poor-and-busy': 'other/Poor-and-busy.md'
        - 'Reflections on Pre-Tirement': 'other/Reflections on Pre-Tirement.md'
        - 'The art of Execution 执行力的艺术': 'other/The art of Execution 执行力的艺术.md'
        - 'Who Wants to Be a Millionaire': 'other/Who Wants to Be a Millionaire.md'
        - 'b计划': 'other/b计划.md'
        - 'data structure basic': 'other/data structure basic.md'
        - 'index': 'other/index.md'
        - 'leanpub-auto-the-road-to-ecmascript-6': 'other/leanpub-auto-the-road-to-ecmascript-6.md'
        - '熵增': 'other/熵增.md'
        - '个人选择': 'other/个人选择.md'
        - '人生真相': 'other/人生真相.md'
        - '其他书单': 'other/其他书单.md'
        - '丹尼斯与Unix': 'other/丹尼斯与Unix.md'
        - '詹宏志读书': 'other/詹宏志读书.md'
        - '骡子和人生': 'other/骡子和人生.md'
        - '代码整洁之道 读书笔记': 'other/代码整洁之道 读书笔记.md'
        - '如何变得强大': 'other/如何变得强大.md'
        - '专业教育的兴起': 'other/专业教育的兴起.md'
        - '中国经济的转变': 'other/中国经济的转变.md'
        - '硕士学位的贬值': 'other/硕士学位的贬值.md'
        - '任正非的管理思想': 'other/任正非的管理思想.md'
        - '技术和稳定的工作': 'other/技术和稳定的工作.md'
        - '大学教育和网络文凭': 'other/大学教育和网络文凭.md'
        - '思维导图到深度学习': 'other/思维导图到深度学习.md'
        - '中国的房价会怎么收场': 'other/中国的房价会怎么收场.md'
        - '工业文明对于社会的冲击': 'other/工业文明对于社会的冲击.md'
        - '正态分布和对数正态分布': 'other/正态分布和对数正态分布.md'

    - JS 基础:
        - '01-入门': 'ebook-JS-basic/01-入门.md'
        - '02-数据类型': 'ebook-JS-basic/02-数据类型.md'
        - '03-运算符': 'ebook-JS-basic/03-运算符.md'
        - '04-语法专题': 'ebook-JS-basic/04-语法专题.md'
        - '05-标准库': 'ebook-JS-basic/05-标准库.md'
        - '06-面向对象编程': 'ebook-JS-basic/06-面向对象编程.md'
        - '07-异步操作': 'ebook-JS-basic/07-异步操作.md'
        - '08-DOM': 'ebook-JS-basic/08-DOM.md'
        - '09-Event': 'ebook-JS-basic/09-Event.md'
        - '10-BOM': 'ebook-JS-basic/10-BOM.md'
        - '11-网页元素接口': 'ebook-JS-basic/11-网页元素接口.md'
        - 'readme': 'ebook-JS-basic/readme.md'

    - 网易云课堂笔记:
        - '02-v8引擎回收内存简介': 'ebook-netease-senior-frontend/02-v8引擎回收内存简介.md'
        - '03-node下面的Restful实现': 'ebook-netease-senior-frontend/03-node下面的Restful实现.md'
        - '04-编程思想的提升—如何提高我们代码的可扩展性': 'ebook-netease-senior-frontend/04-编程思想的提升—如何提高我们代码的可扩展性.md'
        - '06-浏览器渲染原理和ssr': 'ebook-netease-senior-frontend/06-浏览器渲染原理和ssr.md'
        - '07-网易真实项目webpack配置解析': 'ebook-netease-senior-frontend/07-网易真实项目webpack配置解析.md'
        - '08-从架构分析API层': 'ebook-netease-senior-frontend/08-从架构分析API层.md'
        - '09-前端负责人的工作内容': 'ebook-netease-senior-frontend/09-前端负责人的工作内容.md'
        - '10-分析源码学架构': 'ebook-netease-senior-frontend/10-分析源码学架构.md'
        - '11-设计模式高质量代码': 'ebook-netease-senior-frontend/11-设计模式高质量代码.md'
        - '12-nodeJS+MongoDB登录系统': 'ebook-netease-senior-frontend/12-nodeJS+MongoDB登录系统.md'
        - '12-nodejs-mongodb-mongoose': 'ebook-netease-senior-frontend/12-nodejs-mongodb-mongoose.md'
        - '13-使用VUE创建组件（没学完）': 'ebook-netease-senior-frontend/13-使用VUE创建组件（没学完）.md'
        - '16-构建自己的脚手架工具': 'ebook-netease-senior-frontend/16-构建自己的脚手架工具.md'
        - '17-webpack编译原理分析': 'ebook-netease-senior-frontend/17-webpack编译原理分析.md'
        - '20-组件封装的基本技能-VUE（没学完）': 'ebook-netease-senior-frontend/20-组件封装的基本技能-VUE（没学完）.md'
        - '21-ssr': 'ebook-netease-senior-frontend/21-ssr.md'
        - '24-单元测试如何做': 'ebook-netease-senior-frontend/24-单元测试如何做.md'
        - '25-基于NodeJS打造Web架构中间层': 'ebook-netease-senior-frontend/25-基于NodeJS打造Web架构中间层.md'
        - '26-webpack的高级技巧': 'ebook-netease-senior-frontend/26-webpack的高级技巧.md'
        - 'readme': 'ebook-netease-senior-frontend/readme.md'

    - 开课吧笔记:
        - '01 性能优化': 'ebook-kaikeba-frontend/01 性能优化.md'
        - '02 前端测试': 'ebook-kaikeba-frontend/02 前端测试.md'
        - '03 设计模式': 'ebook-kaikeba-frontend/03 设计模式.md'
        - '04 数据结构与算法': 'ebook-kaikeba-frontend/04 数据结构与算法.md'
        - '05 面试题': 'ebook-kaikeba-frontend/05 面试题.md'
        - '06 面试技巧': 'ebook-kaikeba-frontend/06 面试技巧.md'

    - 前端工程化笔记:
        - 'README': 'ebook-jstraining-RYF/README.md'
        - 'engineering': 'ebook-jstraining-RYF/engineering.md'
        - 'history': 'ebook-jstraining-RYF/history.md'
        - 'node': 'ebook-jstraining-RYF/node.md'
        - 'preparation': 'ebook-jstraining-RYF/preparation.md'
        - 'react': 'ebook-jstraining-RYF/react.md'

    - JS ES6 语法:
        - '说明': 'ebook-JSES6-RYF/readme.md'
        - '01-介绍': 'ebook-JSES6-RYF/01-介绍.md'
        - '02-变量赋值': 'ebook-JSES6-RYF/02-变量赋值.md'
        - '03-解构赋值': 'ebook-JSES6-RYF/03-解构赋值.md'
        - '04-字符串的扩展': 'ebook-JSES6-RYF/04-字符串的扩展.md'
        - '05-字符串方法': 'ebook-JSES6-RYF/05-字符串方法.md'
        - '06-正则': 'ebook-JSES6-RYF/06-正则.md'
        - '07-数值': 'ebook-JSES6-RYF/07-数值.md'
        - '08-函数': 'ebook-JSES6-RYF/08-函数.md'
        - '09-数组': 'ebook-JSES6-RYF/09-数组.md'
        - '10-对象的新增属性': 'ebook-JSES6-RYF/10-对象的新增属性.md'
        - '11-对象的新增方法': 'ebook-JSES6-RYF/11-对象的新增方法.md'
        - '12-Symbol': 'ebook-JSES6-RYF/12-Symbol.md'
        - '13-Set 和 Map 数据结构': 'ebook-JSES6-RYF/13-Set 和 Map 数据结构.md'
        - '14-Proxy': 'ebook-JSES6-RYF/14-Proxy.md'
        - '15-Reflect': 'ebook-JSES6-RYF/15-Reflect.md'
        - '16-Promise': 'ebook-JSES6-RYF/16-Promise.md'
        - '17-遍历器的循环': 'ebook-JSES6-RYF/17-遍历器的循环.md'
        - '18-Generator': 'ebook-JSES6-RYF/18-Generator.md'
        - '19-Generator异步应用': 'ebook-JSES6-RYF/19-Generator异步应用.md'
        - '20-async 函数': 'ebook-JSES6-RYF/20-async 函数.md'
        - '21-Class 的基本语法': 'ebook-JSES6-RYF/21-Class 的基本语法.md'
        - '22-Class 的继承': 'ebook-JSES6-RYF/22-Class 的继承.md'
        - '23-Module 的语法': 'ebook-JSES6-RYF/23-Module 的语法.md'
        - '24-Module 的加载实现': 'ebook-JSES6-RYF/24-Module 的加载实现.md'
        - '25-编程风格': 'ebook-JSES6-RYF/25-编程风格.md'

    - Javascript 高级教程:
      - '08-window': 'book-JS-primer-code-design/08-window.md'
      - '10-nodes': 'book-JS-primer-code-design/10-nodes.md'
      - '11-choose': 'book-JS-primer-code-design/11-choose.md'
      - '22-高级用法': 'book-JS-primer-code-design/22-高级用法.md'
      - '24-最佳实践': 'book-JS-primer-code-design/24-最佳实践.md'
      - 'readme': 'book-JS-primer-code-design/readme.md'

    - 其他书籍:
      - 'JS-the-good-parts': 'book-JS-The-good-parts/JS-the-good-parts.md'
      - 'curry-function': 'book-JS-The-good-parts/curry-function.md'
      - 'JavaScript 秘密花园': 'ebook-javascript-secret-garden/JavaScript 秘密花园-zh.md'
      - 'readme': 'ebook-javascript-secret-garden/readme.md'
